{{- if and .Values.webhookReceiver.pdb.enabled (eq .Values.deploymentMode "split") }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "paprika.resourceName" (dict "suffix" "webhook-receiver" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "paprika.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: webhook-receiver
spec:
  minAvailable: {{ .Values.webhookReceiver.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "paprika.name" . }}
      app.kubernetes.io/component: webhook-receiver
{{- end }}
