// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/traffic (interfaces: Router)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_traffic.go -package=mocks . Router
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRouter is a mock of Router interface.
type MockRouter struct {
	ctrl     *gomock.Controller
	recorder *MockRouterMockRecorder
	isgomock struct{}
}

// MockRouterMockRecorder is the mock recorder for MockRouter.
type MockRouterMockRecorder struct {
	mock *MockRouter
}

// NewMockRouter creates a new mock instance.
func NewMockRouter(ctrl *gomock.Controller) *MockRouter {
	mock := &MockRouter{ctrl: ctrl}
	mock.recorder = &MockRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouter) EXPECT() *MockRouterMockRecorder {
	return m.recorder
}

// RemoveCanary mocks base method.
func (m *MockRouter) RemoveCanary(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCanary", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCanary indicates an expected call of RemoveCanary.
func (mr *MockRouterMockRecorder) RemoveCanary(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCanary", reflect.TypeOf((*MockRouter)(nil).RemoveCanary), ctx)
}

// RemoveHeaderRoute mocks base method.
func (m *MockRouter) RemoveHeaderRoute(ctx context.Context, header string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveHeaderRoute", ctx, header)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveHeaderRoute indicates an expected call of RemoveHeaderRoute.
func (mr *MockRouterMockRecorder) RemoveHeaderRoute(ctx, header any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveHeaderRoute", reflect.TypeOf((*MockRouter)(nil).RemoveHeaderRoute), ctx, header)
}

// RemoveMirror mocks base method.
func (m *MockRouter) RemoveMirror(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMirror", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMirror indicates an expected call of RemoveMirror.
func (mr *MockRouterMockRecorder) RemoveMirror(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMirror", reflect.TypeOf((*MockRouter)(nil).RemoveMirror), ctx)
}

// SetHeaderRoute mocks base method.
func (m *MockRouter) SetHeaderRoute(ctx context.Context, header, value, service string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeaderRoute", ctx, header, value, service)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeaderRoute indicates an expected call of SetHeaderRoute.
func (mr *MockRouterMockRecorder) SetHeaderRoute(ctx, header, value, service any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeaderRoute", reflect.TypeOf((*MockRouter)(nil).SetHeaderRoute), ctx, header, value, service)
}

// SetMirror mocks base method.
func (m *MockRouter) SetMirror(ctx context.Context, percent int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMirror", ctx, percent)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMirror indicates an expected call of SetMirror.
func (mr *MockRouterMockRecorder) SetMirror(ctx, percent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMirror", reflect.TypeOf((*MockRouter)(nil).SetMirror), ctx, percent)
}

// SetWeight mocks base method.
func (m *MockRouter) SetWeight(ctx context.Context, weight int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWeight", ctx, weight)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWeight indicates an expected call of SetWeight.
func (mr *MockRouterMockRecorder) SetWeight(ctx, weight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWeight", reflect.TypeOf((*MockRouter)(nil).SetWeight), ctx, weight)
}

// Type mocks base method.
func (m *MockRouter) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockRouterMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockRouter)(nil).Type))
}
