// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/traffic (interfaces: Router)

package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRouter is a mock of Router interface.
type MockRouter struct {
	ctrl     *gomock.Controller
	recorder *MockRouterMockRecorder
}

// MockRouterMockRecorder is the mock recorder for MockRouter.
type MockRouterMockRecorder struct {
	mock *MockRouter
}

// NewMockRouter creates a new mock instance.
func NewMockRouter(ctrl *gomock.Controller) *MockRouter {
	mock := &MockRouter{ctrl: ctrl}
	mock.recorder = &MockRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRouter) EXPECT() *MockRouterMockRecorder {
	return m.recorder
}

// SetWeight mocks base method.
func (m *MockRouter) SetWeight(ctx context.Context, weight int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWeight", ctx, weight)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWeight indicates an expected call of SetWeight.
func (mr *MockRouterMockRecorder) SetWeight(ctx, weight any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWeight", reflect.TypeOf((*MockRouter)(nil).SetWeight), ctx, weight)
}

// RemoveCanary mocks base method.
func (m *MockRouter) RemoveCanary(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCanary", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCanary indicates an expected call of RemoveCanary.
func (mr *MockRouterMockRecorder) RemoveCanary(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCanary", reflect.TypeOf((*MockRouter)(nil).RemoveCanary), ctx)
}

// Type mocks base method.
func (m *MockRouter) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockRouterMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockRouter)(nil).Type))
}
