// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/internal/controller/pipelines (interfaces: AgentClient)
//
// Generated by this command:
//
//	mockgen -destination=mocks/agent_client.go -package=mocks -typed . AgentClient
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	agent "github.com/benebsworth/paprika/internal/agent/server"
	gomock "go.uber.org/mock/gomock"
)

// MockAgentClient is a mock of AgentClient interface.
type MockAgentClient struct {
	ctrl     *gomock.Controller
	recorder *MockAgentClientMockRecorder
	isgomock struct{}
}

// MockAgentClientMockRecorder is the mock recorder for MockAgentClient.
type MockAgentClientMockRecorder struct {
	mock *MockAgentClient
}

// NewMockAgentClient creates a new mock instance.
func NewMockAgentClient(ctrl *gomock.Controller) *MockAgentClient {
	mock := &MockAgentClient{ctrl: ctrl}
	mock.recorder = &MockAgentClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAgentClient) EXPECT() *MockAgentClientMockRecorder {
	return m.recorder
}

// Apply mocks base method.
func (m *MockAgentClient) Apply(ctx context.Context, req *agent.ApplyRequest) (*agent.ApplyResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Apply", ctx, req)
	ret0, _ := ret[0].(*agent.ApplyResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Apply indicates an expected call of Apply.
func (mr *MockAgentClientMockRecorder) Apply(ctx, req any) *MockAgentClientApplyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Apply", reflect.TypeOf((*MockAgentClient)(nil).Apply), ctx, req)
	return &MockAgentClientApplyCall{Call: call}
}

// MockAgentClientApplyCall wrap *gomock.Call
type MockAgentClientApplyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAgentClientApplyCall) Return(arg0 *agent.ApplyResponse, arg1 error) *MockAgentClientApplyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAgentClientApplyCall) Do(f func(context.Context, *agent.ApplyRequest) (*agent.ApplyResponse, error)) *MockAgentClientApplyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAgentClientApplyCall) DoAndReturn(f func(context.Context, *agent.ApplyRequest) (*agent.ApplyResponse, error)) *MockAgentClientApplyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Enabled mocks base method.
func (m *MockAgentClient) Enabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled.
func (mr *MockAgentClientMockRecorder) Enabled() *MockAgentClientEnabledCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*MockAgentClient)(nil).Enabled))
	return &MockAgentClientEnabledCall{Call: call}
}

// MockAgentClientEnabledCall wrap *gomock.Call
type MockAgentClientEnabledCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAgentClientEnabledCall) Return(arg0 bool) *MockAgentClientEnabledCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAgentClientEnabledCall) Do(f func() bool) *MockAgentClientEnabledCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAgentClientEnabledCall) DoAndReturn(f func() bool) *MockAgentClientEnabledCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Health mocks base method.
func (m *MockAgentClient) Health(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Health", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Health indicates an expected call of Health.
func (mr *MockAgentClientMockRecorder) Health(ctx any) *MockAgentClientHealthCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockAgentClient)(nil).Health), ctx)
	return &MockAgentClientHealthCall{Call: call}
}

// MockAgentClientHealthCall wrap *gomock.Call
type MockAgentClientHealthCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockAgentClientHealthCall) Return(arg0 error) *MockAgentClientHealthCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockAgentClientHealthCall) Do(f func(context.Context) error) *MockAgentClientHealthCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockAgentClientHealthCall) DoAndReturn(f func(context.Context) error) *MockAgentClientHealthCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
