// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/internal/controller/pipelines (interfaces: ClusterClientManager)
//
// Generated by this command:
//
//	mockgen -destination=mocks/cluster_client_manager.go -package=mocks -typed . ClusterClientManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	dynamic "k8s.io/client-go/dynamic"
	rest "k8s.io/client-go/rest"
)

// MockClusterClientManager is a mock of ClusterClientManager interface.
type MockClusterClientManager struct {
	ctrl     *gomock.Controller
	recorder *MockClusterClientManagerMockRecorder
	isgomock struct{}
}

// MockClusterClientManagerMockRecorder is the mock recorder for MockClusterClientManager.
type MockClusterClientManagerMockRecorder struct {
	mock *MockClusterClientManager
}

// NewMockClusterClientManager creates a new mock instance.
func NewMockClusterClientManager(ctrl *gomock.Controller) *MockClusterClientManager {
	mock := &MockClusterClientManager{ctrl: ctrl}
	mock.recorder = &MockClusterClientManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterClientManager) EXPECT() *MockClusterClientManagerMockRecorder {
	return m.recorder
}

// GetClient mocks base method.
func (m *MockClusterClientManager) GetClient(ctx context.Context, kubeconfigSecret, namespace string) (dynamic.Interface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", ctx, kubeconfigSecret, namespace)
	ret0, _ := ret[0].(dynamic.Interface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockClusterClientManagerMockRecorder) GetClient(ctx, kubeconfigSecret, namespace any) *MockClusterClientManagerGetClientCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockClusterClientManager)(nil).GetClient), ctx, kubeconfigSecret, namespace)
	return &MockClusterClientManagerGetClientCall{Call: call}
}

// MockClusterClientManagerGetClientCall wrap *gomock.Call
type MockClusterClientManagerGetClientCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClusterClientManagerGetClientCall) Return(arg0 dynamic.Interface, arg1 error) *MockClusterClientManagerGetClientCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClusterClientManagerGetClientCall) Do(f func(context.Context, string, string) (dynamic.Interface, error)) *MockClusterClientManagerGetClientCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClusterClientManagerGetClientCall) DoAndReturn(f func(context.Context, string, string) (dynamic.Interface, error)) *MockClusterClientManagerGetClientCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetRestConfig mocks base method.
func (m *MockClusterClientManager) GetRestConfig(ctx context.Context, kubeconfigSecret, namespace string) (*rest.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestConfig", ctx, kubeconfigSecret, namespace)
	ret0, _ := ret[0].(*rest.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestConfig indicates an expected call of GetRestConfig.
func (mr *MockClusterClientManagerMockRecorder) GetRestConfig(ctx, kubeconfigSecret, namespace any) *MockClusterClientManagerGetRestConfigCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestConfig", reflect.TypeOf((*MockClusterClientManager)(nil).GetRestConfig), ctx, kubeconfigSecret, namespace)
	return &MockClusterClientManagerGetRestConfigCall{Call: call}
}

// MockClusterClientManagerGetRestConfigCall wrap *gomock.Call
type MockClusterClientManagerGetRestConfigCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClusterClientManagerGetRestConfigCall) Return(arg0 *rest.Config, arg1 error) *MockClusterClientManagerGetRestConfigCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClusterClientManagerGetRestConfigCall) Do(f func(context.Context, string, string) (*rest.Config, error)) *MockClusterClientManagerGetRestConfigCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClusterClientManagerGetRestConfigCall) DoAndReturn(f func(context.Context, string, string) (*rest.Config, error)) *MockClusterClientManagerGetRestConfigCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
