// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/internal/controller (interfaces: ClusterClientManager)
//
// Generated by this command:
//
//	mockgen -destination=mocks/cluster_client_manager.go -package=mocks . ClusterClientManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	dynamic "k8s.io/client-go/dynamic"
	rest "k8s.io/client-go/rest"
)

// MockClusterClientManager is a mock of ClusterClientManager interface.
type MockClusterClientManager struct {
	ctrl     *gomock.Controller
	recorder *MockClusterClientManagerMockRecorder
	isgomock struct{}
}

// MockClusterClientManagerMockRecorder is the mock recorder for MockClusterClientManager.
type MockClusterClientManagerMockRecorder struct {
	mock *MockClusterClientManager
}

// NewMockClusterClientManager creates a new mock instance.
func NewMockClusterClientManager(ctrl *gomock.Controller) *MockClusterClientManager {
	mock := &MockClusterClientManager{ctrl: ctrl}
	mock.recorder = &MockClusterClientManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClusterClientManager) EXPECT() *MockClusterClientManagerMockRecorder {
	return m.recorder
}

// GetClient mocks base method.
func (m *MockClusterClientManager) GetClient(ctx context.Context, kubeconfigSecret, namespace string) (dynamic.Interface, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", ctx, kubeconfigSecret, namespace)
	ret0, _ := ret[0].(dynamic.Interface)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockClusterClientManagerMockRecorder) GetClient(ctx, kubeconfigSecret, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockClusterClientManager)(nil).GetClient), ctx, kubeconfigSecret, namespace)
}

// GetRestConfig mocks base method.
func (m *MockClusterClientManager) GetRestConfig(ctx context.Context, kubeconfigSecret, namespace string) (*rest.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRestConfig", ctx, kubeconfigSecret, namespace)
	ret0, _ := ret[0].(*rest.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRestConfig indicates an expected call of GetRestConfig.
func (mr *MockClusterClientManagerMockRecorder) GetRestConfig(ctx, kubeconfigSecret, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRestConfig", reflect.TypeOf((*MockClusterClientManager)(nil).GetRestConfig), ctx, kubeconfigSecret, namespace)
}
