// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/internal/controller/pipelines (interfaces: DiffEngine)
//
// Generated by this command:
//
//	mockgen -destination=mocks/diff_engine.go -package=mocks -typed . DiffEngine
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	engine "github.com/benebsworth/paprika/internal/engine"
	gomock "go.uber.org/mock/gomock"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
)

// MockDiffEngine is a mock of DiffEngine interface.
type MockDiffEngine struct {
	ctrl     *gomock.Controller
	recorder *MockDiffEngineMockRecorder
	isgomock struct{}
}

// MockDiffEngineMockRecorder is the mock recorder for MockDiffEngine.
type MockDiffEngineMockRecorder struct {
	mock *MockDiffEngine
}

// NewMockDiffEngine creates a new mock instance.
func NewMockDiffEngine(ctrl *gomock.Controller) *MockDiffEngine {
	mock := &MockDiffEngine{ctrl: ctrl}
	mock.recorder = &MockDiffEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiffEngine) EXPECT() *MockDiffEngineMockRecorder {
	return m.recorder
}

// ComputeDiff mocks base method.
func (m *MockDiffEngine) ComputeDiff(ctx context.Context, desired []unstructured.Unstructured, opts engine.DiffOptions) (*engine.DiffResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ComputeDiff", ctx, desired, opts)
	ret0, _ := ret[0].(*engine.DiffResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ComputeDiff indicates an expected call of ComputeDiff.
func (mr *MockDiffEngineMockRecorder) ComputeDiff(ctx, desired, opts any) *MockDiffEngineComputeDiffCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ComputeDiff", reflect.TypeOf((*MockDiffEngine)(nil).ComputeDiff), ctx, desired, opts)
	return &MockDiffEngineComputeDiffCall{Call: call}
}

// MockDiffEngineComputeDiffCall wrap *gomock.Call
type MockDiffEngineComputeDiffCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDiffEngineComputeDiffCall) Return(arg0 *engine.DiffResult, arg1 error) *MockDiffEngineComputeDiffCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDiffEngineComputeDiffCall) Do(f func(context.Context, []unstructured.Unstructured, engine.DiffOptions) (*engine.DiffResult, error)) *MockDiffEngineComputeDiffCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDiffEngineComputeDiffCall) DoAndReturn(f func(context.Context, []unstructured.Unstructured, engine.DiffOptions) (*engine.DiffResult, error)) *MockDiffEngineComputeDiffCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
