// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/internal/controller/pipelines (interfaces: S3SourceResolver)
//
// Generated by this command:
//
//	mockgen -destination=mocks/s3_source_resolver.go -package=mocks . S3SourceResolver
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	source "github.com/benebsworth/paprika/internal/source"
	gomock "go.uber.org/mock/gomock"
)

// MockS3SourceResolver is a mock of S3SourceResolver interface.
type MockS3SourceResolver struct {
	ctrl     *gomock.Controller
	recorder *MockS3SourceResolverMockRecorder
	isgomock struct{}
}

// MockS3SourceResolverMockRecorder is the mock recorder for MockS3SourceResolver.
type MockS3SourceResolverMockRecorder struct {
	mock *MockS3SourceResolver
}

// NewMockS3SourceResolver creates a new mock instance.
func NewMockS3SourceResolver(ctrl *gomock.Controller) *MockS3SourceResolver {
	mock := &MockS3SourceResolver{ctrl: ctrl}
	mock.recorder = &MockS3SourceResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockS3SourceResolver) EXPECT() *MockS3SourceResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockS3SourceResolver) Resolve(ctx context.Context) (*source.ResolveResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx)
	ret0, _ := ret[0].(*source.ResolveResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockS3SourceResolverMockRecorder) Resolve(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockS3SourceResolver)(nil).Resolve), ctx)
}
