// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/internal/controller/pipelines (interfaces: TemplateRenderer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/template_renderer.go -package=mocks -typed . TemplateRenderer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/benebsworth/paprika/api/pipelines/v1alpha1"
	source "github.com/benebsworth/paprika/internal/source"
	gomock "go.uber.org/mock/gomock"
)

// MockTemplateRenderer is a mock of TemplateRenderer interface.
type MockTemplateRenderer struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateRendererMockRecorder
	isgomock struct{}
}

// MockTemplateRendererMockRecorder is the mock recorder for MockTemplateRenderer.
type MockTemplateRendererMockRecorder struct {
	mock *MockTemplateRenderer
}

// NewMockTemplateRenderer creates a new mock instance.
func NewMockTemplateRenderer(ctrl *gomock.Controller) *MockTemplateRenderer {
	mock := &MockTemplateRenderer{ctrl: ctrl}
	mock.recorder = &MockTemplateRendererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateRenderer) EXPECT() *MockTemplateRendererMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MockTemplateRenderer) Render(ctx context.Context, tmpl *v1alpha1.Template, params map[string]string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", ctx, tmpl, params)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Render indicates an expected call of Render.
func (mr *MockTemplateRendererMockRecorder) Render(ctx, tmpl, params any) *MockTemplateRendererRenderCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockTemplateRenderer)(nil).Render), ctx, tmpl, params)
	return &MockTemplateRendererRenderCall{Call: call}
}

// MockTemplateRendererRenderCall wrap *gomock.Call
type MockTemplateRendererRenderCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTemplateRendererRenderCall) Return(arg0 []byte, arg1 error) *MockTemplateRendererRenderCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTemplateRendererRenderCall) Do(f func(context.Context, *v1alpha1.Template, map[string]string) ([]byte, error)) *MockTemplateRendererRenderCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTemplateRendererRenderCall) DoAndReturn(f func(context.Context, *v1alpha1.Template, map[string]string) ([]byte, error)) *MockTemplateRendererRenderCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RenderAll mocks base method.
func (m *MockTemplateRenderer) RenderAll(ctx context.Context, templates []v1alpha1.Template, params map[string]string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderAll", ctx, templates, params)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderAll indicates an expected call of RenderAll.
func (mr *MockTemplateRendererMockRecorder) RenderAll(ctx, templates, params any) *MockTemplateRendererRenderAllCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderAll", reflect.TypeOf((*MockTemplateRenderer)(nil).RenderAll), ctx, templates, params)
	return &MockTemplateRendererRenderAllCall{Call: call}
}

// MockTemplateRendererRenderAllCall wrap *gomock.Call
type MockTemplateRendererRenderAllCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTemplateRendererRenderAllCall) Return(arg0 []byte, arg1 error) *MockTemplateRendererRenderAllCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTemplateRendererRenderAllCall) Do(f func(context.Context, []v1alpha1.Template, map[string]string) ([]byte, error)) *MockTemplateRendererRenderAllCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTemplateRendererRenderAllCall) DoAndReturn(f func(context.Context, []v1alpha1.Template, map[string]string) ([]byte, error)) *MockTemplateRendererRenderAllCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RenderHelmChart mocks base method.
func (m *MockTemplateRenderer) RenderHelmChart(ctx context.Context, chartName, chartRepo, chartVersion string, values map[string]string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderHelmChart", ctx, chartName, chartRepo, chartVersion, values)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderHelmChart indicates an expected call of RenderHelmChart.
func (mr *MockTemplateRendererMockRecorder) RenderHelmChart(ctx, chartName, chartRepo, chartVersion, values any) *MockTemplateRendererRenderHelmChartCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderHelmChart", reflect.TypeOf((*MockTemplateRenderer)(nil).RenderHelmChart), ctx, chartName, chartRepo, chartVersion, values)
	return &MockTemplateRendererRenderHelmChartCall{Call: call}
}

// MockTemplateRendererRenderHelmChartCall wrap *gomock.Call
type MockTemplateRendererRenderHelmChartCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTemplateRendererRenderHelmChartCall) Return(arg0 []byte, arg1 error) *MockTemplateRendererRenderHelmChartCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTemplateRendererRenderHelmChartCall) Do(f func(context.Context, string, string, string, map[string]string) ([]byte, error)) *MockTemplateRendererRenderHelmChartCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTemplateRendererRenderHelmChartCall) DoAndReturn(f func(context.Context, string, string, string, map[string]string) ([]byte, error)) *MockTemplateRendererRenderHelmChartCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ResolveSource mocks base method.
func (m *MockTemplateRenderer) ResolveSource(ctx context.Context, tmpl *v1alpha1.Template) (*source.ResolveResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveSource", ctx, tmpl)
	ret0, _ := ret[0].(*source.ResolveResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveSource indicates an expected call of ResolveSource.
func (mr *MockTemplateRendererMockRecorder) ResolveSource(ctx, tmpl any) *MockTemplateRendererResolveSourceCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveSource", reflect.TypeOf((*MockTemplateRenderer)(nil).ResolveSource), ctx, tmpl)
	return &MockTemplateRendererResolveSourceCall{Call: call}
}

// MockTemplateRendererResolveSourceCall wrap *gomock.Call
type MockTemplateRendererResolveSourceCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTemplateRendererResolveSourceCall) Return(arg0 *source.ResolveResult, arg1 error) *MockTemplateRendererResolveSourceCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTemplateRendererResolveSourceCall) Do(f func(context.Context, *v1alpha1.Template) (*source.ResolveResult, error)) *MockTemplateRendererResolveSourceCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTemplateRendererResolveSourceCall) DoAndReturn(f func(context.Context, *v1alpha1.Template) (*source.ResolveResult, error)) *MockTemplateRendererResolveSourceCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
