// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/internal/controller/pipelines (interfaces: WorkflowEngine)
//
// Generated by this command:
//
//	mockgen -destination=mocks/workflow_engine.go -package=mocks -typed . WorkflowEngine
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/benebsworth/paprika/api/pipelines/v1alpha1"
	gomock "go.uber.org/mock/gomock"
	v1 "k8s.io/api/batch/v1"
)

// MockWorkflowEngine is a mock of WorkflowEngine interface.
type MockWorkflowEngine struct {
	ctrl     *gomock.Controller
	recorder *MockWorkflowEngineMockRecorder
	isgomock struct{}
}

// MockWorkflowEngineMockRecorder is the mock recorder for MockWorkflowEngine.
type MockWorkflowEngineMockRecorder struct {
	mock *MockWorkflowEngine
}

// NewMockWorkflowEngine creates a new mock instance.
func NewMockWorkflowEngine(ctrl *gomock.Controller) *MockWorkflowEngine {
	mock := &MockWorkflowEngine{ctrl: ctrl}
	mock.recorder = &MockWorkflowEngineMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkflowEngine) EXPECT() *MockWorkflowEngineMockRecorder {
	return m.recorder
}

// CreateStepJob mocks base method.
func (m *MockWorkflowEngine) CreateStepJob(ctx context.Context, step *v1alpha1.PipelineStep, pipelineName string) (*v1.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStepJob", ctx, step, pipelineName)
	ret0, _ := ret[0].(*v1.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStepJob indicates an expected call of CreateStepJob.
func (mr *MockWorkflowEngineMockRecorder) CreateStepJob(ctx, step, pipelineName any) *MockWorkflowEngineCreateStepJobCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStepJob", reflect.TypeOf((*MockWorkflowEngine)(nil).CreateStepJob), ctx, step, pipelineName)
	return &MockWorkflowEngineCreateStepJobCall{Call: call}
}

// MockWorkflowEngineCreateStepJobCall wrap *gomock.Call
type MockWorkflowEngineCreateStepJobCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkflowEngineCreateStepJobCall) Return(arg0 *v1.Job, arg1 error) *MockWorkflowEngineCreateStepJobCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkflowEngineCreateStepJobCall) Do(f func(context.Context, *v1alpha1.PipelineStep, string) (*v1.Job, error)) *MockWorkflowEngineCreateStepJobCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkflowEngineCreateStepJobCall) DoAndReturn(f func(context.Context, *v1alpha1.PipelineStep, string) (*v1.Job, error)) *MockWorkflowEngineCreateStepJobCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetStepLogs mocks base method.
func (m *MockWorkflowEngine) GetStepLogs(ctx context.Context, pipelineName, stepName string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStepLogs", ctx, pipelineName, stepName)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStepLogs indicates an expected call of GetStepLogs.
func (mr *MockWorkflowEngineMockRecorder) GetStepLogs(ctx, pipelineName, stepName any) *MockWorkflowEngineGetStepLogsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStepLogs", reflect.TypeOf((*MockWorkflowEngine)(nil).GetStepLogs), ctx, pipelineName, stepName)
	return &MockWorkflowEngineGetStepLogsCall{Call: call}
}

// MockWorkflowEngineGetStepLogsCall wrap *gomock.Call
type MockWorkflowEngineGetStepLogsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkflowEngineGetStepLogsCall) Return(arg0 string, arg1 error) *MockWorkflowEngineGetStepLogsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkflowEngineGetStepLogsCall) Do(f func(context.Context, string, string) (string, error)) *MockWorkflowEngineGetStepLogsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkflowEngineGetStepLogsCall) DoAndReturn(f func(context.Context, string, string) (string, error)) *MockWorkflowEngineGetStepLogsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RunPipeline mocks base method.
func (m *MockWorkflowEngine) RunPipeline(ctx context.Context, pipeline *v1alpha1.Pipeline) ([]v1alpha1.StepStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunPipeline", ctx, pipeline)
	ret0, _ := ret[0].([]v1alpha1.StepStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RunPipeline indicates an expected call of RunPipeline.
func (mr *MockWorkflowEngineMockRecorder) RunPipeline(ctx, pipeline any) *MockWorkflowEngineRunPipelineCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunPipeline", reflect.TypeOf((*MockWorkflowEngine)(nil).RunPipeline), ctx, pipeline)
	return &MockWorkflowEngineRunPipelineCall{Call: call}
}

// MockWorkflowEngineRunPipelineCall wrap *gomock.Call
type MockWorkflowEngineRunPipelineCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWorkflowEngineRunPipelineCall) Return(arg0 []v1alpha1.StepStatus, arg1 error) *MockWorkflowEngineRunPipelineCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWorkflowEngineRunPipelineCall) Do(f func(context.Context, *v1alpha1.Pipeline) ([]v1alpha1.StepStatus, error)) *MockWorkflowEngineRunPipelineCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWorkflowEngineRunPipelineCall) DoAndReturn(f func(context.Context, *v1alpha1.Pipeline) ([]v1alpha1.StepStatus, error)) *MockWorkflowEngineRunPipelineCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
