---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pipelines-paprika-io-v1alpha1-application
  failurePolicy: Fail
  name: mapplication-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-paprika-io-v1alpha1-appproject
  failurePolicy: Fail
  name: mappproject-v1alpha1.kb.io
  rules:
  - apiGroups:
    - core.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - appprojects
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pipelines-paprika-io-v1alpha1-pipeline
  failurePolicy: Fail
  name: mpipeline-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pipelines
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-policy-paprika-io-v1alpha1-policy
  failurePolicy: Fail
  name: mpolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - policy.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - policies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pipelines-paprika-io-v1alpha1-release
  failurePolicy: Fail
  name: mrelease-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - releases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-paprika-io-v1alpha1-repository
  failurePolicy: Fail
  name: mrepository-v1alpha1.kb.io
  rules:
  - apiGroups:
    - core.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - repositories
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-rollouts-paprika-io-v1alpha1-rollout
  failurePolicy: Fail
  name: mrollout.kb.io
  rules:
  - apiGroups:
    - rollouts.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rollouts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pipelines-paprika-io-v1alpha1-stage
  failurePolicy: Fail
  name: mstage-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - stages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pipelines-paprika-io-v1alpha1-template
  failurePolicy: Fail
  name: mtemplate-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - templates
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelines-paprika-io-v1alpha1-application
  failurePolicy: Fail
  name: vapplication-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-paprika-io-v1alpha1-appproject
  failurePolicy: Fail
  name: vappproject-v1alpha1.kb.io
  rules:
  - apiGroups:
    - core.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - appprojects
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelines-paprika-io-v1alpha1-pipeline
  failurePolicy: Fail
  name: vpipeline-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pipelines
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-policy-paprika-io-v1alpha1-policy
  failurePolicy: Fail
  name: vpolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - policy.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - policies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelines-paprika-io-v1alpha1-release
  failurePolicy: Fail
  name: vrelease-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - releases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-paprika-io-v1alpha1-repository
  failurePolicy: Fail
  name: vrepository-v1alpha1.kb.io
  rules:
  - apiGroups:
    - core.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - repositories
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-rollouts-paprika-io-v1alpha1-rollout
  failurePolicy: Fail
  name: vrollout.kb.io
  rules:
  - apiGroups:
    - rollouts.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rollouts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelines-paprika-io-v1alpha1-stage
  failurePolicy: Fail
  name: vstage-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - stages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelines-paprika-io-v1alpha1-template
  failurePolicy: Fail
  name: vtemplate-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - templates
  sideEffects: None
