---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pipelines-paprika-io-v1alpha1-analysisrun
  failurePolicy: Fail
  name: manalysisrun-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - analysisruns
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pipelines-paprika-io-v1alpha1-analysistemplate
  failurePolicy: Fail
  name: manalysistemplate-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - analysistemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pipelines-paprika-io-v1alpha1-application
  failurePolicy: Fail
  name: mapplication-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pipelines-paprika-io-v1alpha1-applicationset
  failurePolicy: Fail
  name: mapplicationset-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applicationsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-paprika-io-v1alpha1-appproject
  failurePolicy: Fail
  name: mappproject-v1alpha1.kb.io
  rules:
  - apiGroups:
    - core.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - appprojects
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pipelines-paprika-io-v1alpha1-artifact
  failurePolicy: Fail
  name: martifact-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - artifacts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-clusters-paprika-io-v1alpha1-cluster
  failurePolicy: Fail
  name: mcluster-v1alpha1.kb.io
  rules:
  - apiGroups:
    - clusters.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pipelines-paprika-io-v1alpha1-conftestpolicy
  failurePolicy: Fail
  name: mconftestpolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - conftestpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-featureflags-paprika-io-v1alpha1-featureflag
  failurePolicy: Fail
  name: mfeatureflag-v1alpha1.kb.io
  rules:
  - apiGroups:
    - featureflags.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - featureflags
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-featureflags-paprika-io-v1alpha1-featureflagbinding
  failurePolicy: Fail
  name: mfeatureflagbinding-v1alpha1.kb.io
  rules:
  - apiGroups:
    - featureflags.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - featureflagbindings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pipelines-paprika-io-v1alpha1-notificationconfig
  failurePolicy: Fail
  name: mnotificationconfig-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - notificationconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pipelines-paprika-io-v1alpha1-pipeline
  failurePolicy: Fail
  name: mpipeline-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pipelines
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-policy-paprika-io-v1alpha1-policy
  failurePolicy: Fail
  name: mpolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - policy.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - policies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pipelines-paprika-io-v1alpha1-release
  failurePolicy: Fail
  name: mrelease-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - releases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-core-paprika-io-v1alpha1-repository
  failurePolicy: Fail
  name: mrepository-v1alpha1.kb.io
  rules:
  - apiGroups:
    - core.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - repositories
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-rollouts-paprika-io-v1alpha1-rollout
  failurePolicy: Fail
  name: mrollout-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rollouts.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rollouts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pipelines-paprika-io-v1alpha1-stage
  failurePolicy: Fail
  name: mstage-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - stages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-pipelines-paprika-io-v1alpha1-template
  failurePolicy: Fail
  name: mtemplate-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - templates
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelines-paprika-io-v1alpha1-analysisrun
  failurePolicy: Fail
  name: vanalysisrun-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - analysisruns
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelines-paprika-io-v1alpha1-analysistemplate
  failurePolicy: Fail
  name: vanalysistemplate-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - analysistemplates
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelines-paprika-io-v1alpha1-application
  failurePolicy: Fail
  name: vapplication-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelines-paprika-io-v1alpha1-applicationset
  failurePolicy: Fail
  name: vapplicationset-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applicationsets
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-paprika-io-v1alpha1-appproject
  failurePolicy: Fail
  name: vappproject-v1alpha1.kb.io
  rules:
  - apiGroups:
    - core.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - appprojects
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelines-paprika-io-v1alpha1-artifact
  failurePolicy: Fail
  name: vartifact-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - artifacts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-clusters-paprika-io-v1alpha1-cluster
  failurePolicy: Fail
  name: vcluster-v1alpha1.kb.io
  rules:
  - apiGroups:
    - clusters.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelines-paprika-io-v1alpha1-conftestpolicy
  failurePolicy: Fail
  name: vconftestpolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - conftestpolicies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-featureflags-paprika-io-v1alpha1-featureflag
  failurePolicy: Fail
  name: vfeatureflag-v1alpha1.kb.io
  rules:
  - apiGroups:
    - featureflags.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - featureflags
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-featureflags-paprika-io-v1alpha1-featureflagbinding
  failurePolicy: Fail
  name: vfeatureflagbinding-v1alpha1.kb.io
  rules:
  - apiGroups:
    - featureflags.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - featureflagbindings
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelines-paprika-io-v1alpha1-notificationconfig
  failurePolicy: Fail
  name: vnotificationconfig-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - notificationconfigs
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelines-paprika-io-v1alpha1-pipeline
  failurePolicy: Fail
  name: vpipeline-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pipelines
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-policy-paprika-io-v1alpha1-policy
  failurePolicy: Fail
  name: vpolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - policy.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - policies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelines-paprika-io-v1alpha1-release
  failurePolicy: Fail
  name: vrelease-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - releases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-core-paprika-io-v1alpha1-repository
  failurePolicy: Fail
  name: vrepository-v1alpha1.kb.io
  rules:
  - apiGroups:
    - core.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - repositories
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-rollouts-paprika-io-v1alpha1-rollout
  failurePolicy: Fail
  name: vrollout-v1alpha1.kb.io
  rules:
  - apiGroups:
    - rollouts.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - rollouts
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelines-paprika-io-v1alpha1-stage
  failurePolicy: Fail
  name: vstage-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - stages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-pipelines-paprika-io-v1alpha1-template
  failurePolicy: Fail
  name: vtemplate-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - templates
  sideEffects: None
