{{- if .Values.webhook.enabled }}
{{- $failurePolicy := .Values.webhook.failurePolicy | default "Fail" }}
{{- $timeoutSeconds := .Values.webhook.timeoutSeconds | default 10 }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  annotations:
    {{- if .Values.certManager.enable }}
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/{{ include "paprika.resourceName" (dict "suffix" "serving-cert" "context" $) }}
    {{- end }}
  name: {{ include "paprika.resourceName" (dict "suffix" "validating-webhook-configuration" "context" $) }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "paprika.resourceName" (dict "suffix" "webhook-service" "context" $) }}
      namespace: {{ .Release.Namespace }}
      path: /validate-pipelines-paprika-io-v1alpha1-application
  failurePolicy: {{ $failurePolicy }}
  timeoutSeconds: {{ $timeoutSeconds }}
  name: vapplication-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - applications
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "paprika.resourceName" (dict "suffix" "webhook-service" "context" $) }}
      namespace: {{ .Release.Namespace }}
      path: /validate-core-paprika-io-v1alpha1-appproject
  failurePolicy: {{ $failurePolicy }}
  timeoutSeconds: {{ $timeoutSeconds }}
  name: vappproject-v1alpha1.kb.io
  rules:
  - apiGroups:
    - core.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - appprojects
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "paprika.resourceName" (dict "suffix" "webhook-service" "context" $) }}
      namespace: {{ .Release.Namespace }}
      path: /validate-pipelines-paprika-io-v1alpha1-pipeline
  failurePolicy: {{ $failurePolicy }}
  timeoutSeconds: {{ $timeoutSeconds }}
  name: vpipeline-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - pipelines
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "paprika.resourceName" (dict "suffix" "webhook-service" "context" $) }}
      namespace: {{ .Release.Namespace }}
      path: /validate-policy-paprika-io-v1alpha1-policy
  failurePolicy: {{ $failurePolicy }}
  timeoutSeconds: {{ $timeoutSeconds }}
  name: vpolicy-v1alpha1.kb.io
  rules:
  - apiGroups:
    - policy.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - policies
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "paprika.resourceName" (dict "suffix" "webhook-service" "context" $) }}
      namespace: {{ .Release.Namespace }}
      path: /validate-pipelines-paprika-io-v1alpha1-release
  failurePolicy: {{ $failurePolicy }}
  timeoutSeconds: {{ $timeoutSeconds }}
  name: vrelease-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - releases
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "paprika.resourceName" (dict "suffix" "webhook-service" "context" $) }}
      namespace: {{ .Release.Namespace }}
      path: /validate-core-paprika-io-v1alpha1-repository
  failurePolicy: {{ $failurePolicy }}
  timeoutSeconds: {{ $timeoutSeconds }}
  name: vrepository-v1alpha1.kb.io
  rules:
  - apiGroups:
    - core.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - repositories
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "paprika.resourceName" (dict "suffix" "webhook-service" "context" $) }}
      namespace: {{ .Release.Namespace }}
      path: /validate-pipelines-paprika-io-v1alpha1-stage
  failurePolicy: {{ $failurePolicy }}
  timeoutSeconds: {{ $timeoutSeconds }}
  name: vstage-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - stages
  sideEffects: None
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "paprika.resourceName" (dict "suffix" "webhook-service" "context" $) }}
      namespace: {{ .Release.Namespace }}
      path: /validate-pipelines-paprika-io-v1alpha1-template
  failurePolicy: {{ $failurePolicy }}
  timeoutSeconds: {{ $timeoutSeconds }}
  name: vtemplate-v1alpha1.kb.io
  rules:
  - apiGroups:
    - pipelines.paprika.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - templates
  sideEffects: None
{{- end }}
