// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: paprika/v1/api.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Step struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Image         string                 `protobuf:"bytes,2,opt,name=image,proto3" json:"image,omitempty"`
	Script        string                 `protobuf:"bytes,3,opt,name=script,proto3" json:"script,omitempty"`
	Depends       []string               `protobuf:"bytes,4,rep,name=depends,proto3" json:"depends,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_paprika_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_paprika_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_paprika_v1_api_proto_rawDescGZIP(), []int{0}
}

func (x *Step) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Step) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *Step) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *Step) GetDepends() []string {
	if x != nil {
		return x.Depends
	}
	return nil
}

type StepStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phase         string                 `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	StartedAt     *int64                 `protobuf:"varint,3,opt,name=started_at,json=startedAt,proto3,oneof" json:"started_at,omitempty"`
	CompletedAt   *int64                 `protobuf:"varint,4,opt,name=completed_at,json=completedAt,proto3,oneof" json:"completed_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepStatus) Reset() {
	*x = StepStatus{}
	mi := &file_paprika_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepStatus) ProtoMessage() {}

func (x *StepStatus) ProtoReflect() protoreflect.Message {
	mi := &file_paprika_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepStatus.ProtoReflect.Descriptor instead.
func (*StepStatus) Descriptor() ([]byte, []int) {
	return file_paprika_v1_api_proto_rawDescGZIP(), []int{1}
}

func (x *StepStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StepStatus) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *StepStatus) GetStartedAt() int64 {
	if x != nil && x.StartedAt != nil {
		return *x.StartedAt
	}
	return 0
}

func (x *StepStatus) GetCompletedAt() int64 {
	if x != nil && x.CompletedAt != nil {
		return *x.CompletedAt
	}
	return 0
}

type ArtifactRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_paprika_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_paprika_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_paprika_v1_api_proto_rawDescGZIP(), []int{2}
}

func (x *ArtifactRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ArtifactRef) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type Pipeline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Steps         []*Step                `protobuf:"bytes,4,rep,name=steps,proto3" json:"steps,omitempty"`
	MaxParallel   int32                  `protobuf:"varint,5,opt,name=max_parallel,json=maxParallel,proto3" json:"max_parallel,omitempty"`
	Phase         string                 `protobuf:"bytes,6,opt,name=phase,proto3" json:"phase,omitempty"`
	StepStatuses  []*StepStatus          `protobuf:"bytes,7,rep,name=step_statuses,json=stepStatuses,proto3" json:"step_statuses,omitempty"`
	Artifacts     []*ArtifactRef         `protobuf:"bytes,8,rep,name=artifacts,proto3" json:"artifacts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pipeline) Reset() {
	*x = Pipeline{}
	mi := &file_paprika_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pipeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pipeline) ProtoMessage() {}

func (x *Pipeline) ProtoReflect() protoreflect.Message {
	mi := &file_paprika_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pipeline.ProtoReflect.Descriptor instead.
func (*Pipeline) Descriptor() ([]byte, []int) {
	return file_paprika_v1_api_proto_rawDescGZIP(), []int{3}
}

func (x *Pipeline) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pipeline) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Pipeline) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Pipeline) GetSteps() []*Step {
	if x != nil {
		return x.Steps
	}
	return nil
}

func (x *Pipeline) GetMaxParallel() int32 {
	if x != nil {
		return x.MaxParallel
	}
	return 0
}

func (x *Pipeline) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *Pipeline) GetStepStatuses() []*StepStatus {
	if x != nil {
		return x.StepStatuses
	}
	return nil
}

func (x *Pipeline) GetArtifacts() []*ArtifactRef {
	if x != nil {
		return x.Artifacts
	}
	return nil
}

type Release struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Name             string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace        string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CreatedAt        int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Pipeline         string                 `protobuf:"bytes,4,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Target           string                 `protobuf:"bytes,5,opt,name=target,proto3" json:"target,omitempty"`
	Phase            string                 `protobuf:"bytes,6,opt,name=phase,proto3" json:"phase,omitempty"`
	CurrentStage     string                 `protobuf:"bytes,7,opt,name=current_stage,json=currentStage,proto3" json:"current_stage,omitempty"`
	PromotionHistory []*Promotion           `protobuf:"bytes,8,rep,name=promotion_history,json=promotionHistory,proto3" json:"promotion_history,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Release) Reset() {
	*x = Release{}
	mi := &file_paprika_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Release) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Release) ProtoMessage() {}

func (x *Release) ProtoReflect() protoreflect.Message {
	mi := &file_paprika_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Release.ProtoReflect.Descriptor instead.
func (*Release) Descriptor() ([]byte, []int) {
	return file_paprika_v1_api_proto_rawDescGZIP(), []int{4}
}

func (x *Release) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Release) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Release) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Release) GetPipeline() string {
	if x != nil {
		return x.Pipeline
	}
	return ""
}

func (x *Release) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *Release) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *Release) GetCurrentStage() string {
	if x != nil {
		return x.CurrentStage
	}
	return ""
}

func (x *Release) GetPromotionHistory() []*Promotion {
	if x != nil {
		return x.PromotionHistory
	}
	return nil
}

type Promotion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stage         string                 `protobuf:"bytes,1,opt,name=stage,proto3" json:"stage,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Promotion) Reset() {
	*x = Promotion{}
	mi := &file_paprika_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Promotion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Promotion) ProtoMessage() {}

func (x *Promotion) ProtoReflect() protoreflect.Message {
	mi := &file_paprika_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Promotion.ProtoReflect.Descriptor instead.
func (*Promotion) Descriptor() ([]byte, []int) {
	return file_paprika_v1_api_proto_rawDescGZIP(), []int{5}
}

func (x *Promotion) GetStage() string {
	if x != nil {
		return x.Stage
	}
	return ""
}

func (x *Promotion) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *Promotion) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type Stage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Ring          int32                  `protobuf:"varint,4,opt,name=ring,proto3" json:"ring,omitempty"`
	Phase         string                 `protobuf:"bytes,5,opt,name=phase,proto3" json:"phase,omitempty"`
	StageName     string                 `protobuf:"bytes,6,opt,name=stage_name,json=stageName,proto3" json:"stage_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Stage) Reset() {
	*x = Stage{}
	mi := &file_paprika_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Stage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Stage) ProtoMessage() {}

func (x *Stage) ProtoReflect() protoreflect.Message {
	mi := &file_paprika_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Stage.ProtoReflect.Descriptor instead.
func (*Stage) Descriptor() ([]byte, []int) {
	return file_paprika_v1_api_proto_rawDescGZIP(), []int{6}
}

func (x *Stage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Stage) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Stage) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Stage) GetRing() int32 {
	if x != nil {
		return x.Ring
	}
	return 0
}

func (x *Stage) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *Stage) GetStageName() string {
	if x != nil {
		return x.StageName
	}
	return ""
}

type ListPipelinesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *string                `protobuf:"bytes,1,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelinesRequest) Reset() {
	*x = ListPipelinesRequest{}
	mi := &file_paprika_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelinesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelinesRequest) ProtoMessage() {}

func (x *ListPipelinesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paprika_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelinesRequest.ProtoReflect.Descriptor instead.
func (*ListPipelinesRequest) Descriptor() ([]byte, []int) {
	return file_paprika_v1_api_proto_rawDescGZIP(), []int{7}
}

func (x *ListPipelinesRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type ListPipelinesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pipelines     []*Pipeline            `protobuf:"bytes,1,rep,name=pipelines,proto3" json:"pipelines,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPipelinesResponse) Reset() {
	*x = ListPipelinesResponse{}
	mi := &file_paprika_v1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPipelinesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPipelinesResponse) ProtoMessage() {}

func (x *ListPipelinesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paprika_v1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPipelinesResponse.ProtoReflect.Descriptor instead.
func (*ListPipelinesResponse) Descriptor() ([]byte, []int) {
	return file_paprika_v1_api_proto_rawDescGZIP(), []int{8}
}

func (x *ListPipelinesResponse) GetPipelines() []*Pipeline {
	if x != nil {
		return x.Pipelines
	}
	return nil
}

type ListReleasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *string                `protobuf:"bytes,1,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReleasesRequest) Reset() {
	*x = ListReleasesRequest{}
	mi := &file_paprika_v1_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReleasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReleasesRequest) ProtoMessage() {}

func (x *ListReleasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paprika_v1_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReleasesRequest.ProtoReflect.Descriptor instead.
func (*ListReleasesRequest) Descriptor() ([]byte, []int) {
	return file_paprika_v1_api_proto_rawDescGZIP(), []int{9}
}

func (x *ListReleasesRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type ListReleasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Releases      []*Release             `protobuf:"bytes,1,rep,name=releases,proto3" json:"releases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListReleasesResponse) Reset() {
	*x = ListReleasesResponse{}
	mi := &file_paprika_v1_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListReleasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListReleasesResponse) ProtoMessage() {}

func (x *ListReleasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paprika_v1_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListReleasesResponse.ProtoReflect.Descriptor instead.
func (*ListReleasesResponse) Descriptor() ([]byte, []int) {
	return file_paprika_v1_api_proto_rawDescGZIP(), []int{10}
}

func (x *ListReleasesResponse) GetReleases() []*Release {
	if x != nil {
		return x.Releases
	}
	return nil
}

type ListStagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     *string                `protobuf:"bytes,1,opt,name=namespace,proto3,oneof" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStagesRequest) Reset() {
	*x = ListStagesRequest{}
	mi := &file_paprika_v1_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStagesRequest) ProtoMessage() {}

func (x *ListStagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paprika_v1_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStagesRequest.ProtoReflect.Descriptor instead.
func (*ListStagesRequest) Descriptor() ([]byte, []int) {
	return file_paprika_v1_api_proto_rawDescGZIP(), []int{11}
}

func (x *ListStagesRequest) GetNamespace() string {
	if x != nil && x.Namespace != nil {
		return *x.Namespace
	}
	return ""
}

type ListStagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stages        []*Stage               `protobuf:"bytes,1,rep,name=stages,proto3" json:"stages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStagesResponse) Reset() {
	*x = ListStagesResponse{}
	mi := &file_paprika_v1_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStagesResponse) ProtoMessage() {}

func (x *ListStagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paprika_v1_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStagesResponse.ProtoReflect.Descriptor instead.
func (*ListStagesResponse) Descriptor() ([]byte, []int) {
	return file_paprika_v1_api_proto_rawDescGZIP(), []int{12}
}

func (x *ListStagesResponse) GetStages() []*Stage {
	if x != nil {
		return x.Stages
	}
	return nil
}

var File_paprika_v1_api_proto protoreflect.FileDescriptor

const file_paprika_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x14paprika/v1/api.proto\x12\n" +
	"paprika.v1\"b\n" +
	"\x04Step\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05image\x18\x02 \x01(\tR\x05image\x12\x16\n" +
	"\x06script\x18\x03 \x01(\tR\x06script\x12\x18\n" +
	"\adepends\x18\x04 \x03(\tR\adepends\"\xa2\x01\n" +
	"\n" +
	"StepStatus\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\"\n" +
	"\n" +
	"started_at\x18\x03 \x01(\x03H\x00R\tstartedAt\x88\x01\x01\x12&\n" +
	"\fcompleted_at\x18\x04 \x01(\x03H\x01R\vcompletedAt\x88\x01\x01B\r\n" +
	"\v_started_atB\x0f\n" +
	"\r_completed_at\"5\n" +
	"\vArtifactRef\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\xb0\x02\n" +
	"\bPipeline\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12&\n" +
	"\x05steps\x18\x04 \x03(\v2\x10.paprika.v1.StepR\x05steps\x12!\n" +
	"\fmax_parallel\x18\x05 \x01(\x05R\vmaxParallel\x12\x14\n" +
	"\x05phase\x18\x06 \x01(\tR\x05phase\x12;\n" +
	"\rstep_statuses\x18\a \x03(\v2\x16.paprika.v1.StepStatusR\fstepStatuses\x125\n" +
	"\tartifacts\x18\b \x03(\v2\x17.paprika.v1.ArtifactRefR\tartifacts\"\x8d\x02\n" +
	"\aRelease\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x1a\n" +
	"\bpipeline\x18\x04 \x01(\tR\bpipeline\x12\x16\n" +
	"\x06target\x18\x05 \x01(\tR\x06target\x12\x14\n" +
	"\x05phase\x18\x06 \x01(\tR\x05phase\x12#\n" +
	"\rcurrent_stage\x18\a \x01(\tR\fcurrentStage\x12B\n" +
	"\x11promotion_history\x18\b \x03(\v2\x15.paprika.v1.PromotionR\x10promotionHistory\"W\n" +
	"\tPromotion\x12\x14\n" +
	"\x05stage\x18\x01 \x01(\tR\x05stage\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xa1\x01\n" +
	"\x05Stage\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x1d\n" +
	"\n" +
	"created_at\x18\x03 \x01(\x03R\tcreatedAt\x12\x12\n" +
	"\x04ring\x18\x04 \x01(\x05R\x04ring\x12\x14\n" +
	"\x05phase\x18\x05 \x01(\tR\x05phase\x12\x1d\n" +
	"\n" +
	"stage_name\x18\x06 \x01(\tR\tstageName\"G\n" +
	"\x14ListPipelinesRequest\x12!\n" +
	"\tnamespace\x18\x01 \x01(\tH\x00R\tnamespace\x88\x01\x01B\f\n" +
	"\n" +
	"_namespace\"K\n" +
	"\x15ListPipelinesResponse\x122\n" +
	"\tpipelines\x18\x01 \x03(\v2\x14.paprika.v1.PipelineR\tpipelines\"F\n" +
	"\x13ListReleasesRequest\x12!\n" +
	"\tnamespace\x18\x01 \x01(\tH\x00R\tnamespace\x88\x01\x01B\f\n" +
	"\n" +
	"_namespace\"G\n" +
	"\x14ListReleasesResponse\x12/\n" +
	"\breleases\x18\x01 \x03(\v2\x13.paprika.v1.ReleaseR\breleases\"D\n" +
	"\x11ListStagesRequest\x12!\n" +
	"\tnamespace\x18\x01 \x01(\tH\x00R\tnamespace\x88\x01\x01B\f\n" +
	"\n" +
	"_namespace\"?\n" +
	"\x12ListStagesResponse\x12)\n" +
	"\x06stages\x18\x01 \x03(\v2\x11.paprika.v1.StageR\x06stages2\x86\x02\n" +
	"\x0ePaprikaService\x12T\n" +
	"\rListPipelines\x12 .paprika.v1.ListPipelinesRequest\x1a!.paprika.v1.ListPipelinesResponse\x12Q\n" +
	"\fListReleases\x12\x1f.paprika.v1.ListReleasesRequest\x1a .paprika.v1.ListReleasesResponse\x12K\n" +
	"\n" +
	"ListStages\x12\x1d.paprika.v1.ListStagesRequest\x1a\x1e.paprika.v1.ListStagesResponseB8Z6github.com/benebsworth/paprika/internal/api/paprika/v1b\x06proto3"

var (
	file_paprika_v1_api_proto_rawDescOnce sync.Once
	file_paprika_v1_api_proto_rawDescData []byte
)

func file_paprika_v1_api_proto_rawDescGZIP() []byte {
	file_paprika_v1_api_proto_rawDescOnce.Do(func() {
		file_paprika_v1_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paprika_v1_api_proto_rawDesc), len(file_paprika_v1_api_proto_rawDesc)))
	})
	return file_paprika_v1_api_proto_rawDescData
}

var file_paprika_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_paprika_v1_api_proto_goTypes = []any{
	(*Step)(nil),                  // 0: paprika.v1.Step
	(*StepStatus)(nil),            // 1: paprika.v1.StepStatus
	(*ArtifactRef)(nil),           // 2: paprika.v1.ArtifactRef
	(*Pipeline)(nil),              // 3: paprika.v1.Pipeline
	(*Release)(nil),               // 4: paprika.v1.Release
	(*Promotion)(nil),             // 5: paprika.v1.Promotion
	(*Stage)(nil),                 // 6: paprika.v1.Stage
	(*ListPipelinesRequest)(nil),  // 7: paprika.v1.ListPipelinesRequest
	(*ListPipelinesResponse)(nil), // 8: paprika.v1.ListPipelinesResponse
	(*ListReleasesRequest)(nil),   // 9: paprika.v1.ListReleasesRequest
	(*ListReleasesResponse)(nil),  // 10: paprika.v1.ListReleasesResponse
	(*ListStagesRequest)(nil),     // 11: paprika.v1.ListStagesRequest
	(*ListStagesResponse)(nil),    // 12: paprika.v1.ListStagesResponse
}
var file_paprika_v1_api_proto_depIdxs = []int32{
	0,  // 0: paprika.v1.Pipeline.steps:type_name -> paprika.v1.Step
	1,  // 1: paprika.v1.Pipeline.step_statuses:type_name -> paprika.v1.StepStatus
	2,  // 2: paprika.v1.Pipeline.artifacts:type_name -> paprika.v1.ArtifactRef
	5,  // 3: paprika.v1.Release.promotion_history:type_name -> paprika.v1.Promotion
	3,  // 4: paprika.v1.ListPipelinesResponse.pipelines:type_name -> paprika.v1.Pipeline
	4,  // 5: paprika.v1.ListReleasesResponse.releases:type_name -> paprika.v1.Release
	6,  // 6: paprika.v1.ListStagesResponse.stages:type_name -> paprika.v1.Stage
	7,  // 7: paprika.v1.PaprikaService.ListPipelines:input_type -> paprika.v1.ListPipelinesRequest
	9,  // 8: paprika.v1.PaprikaService.ListReleases:input_type -> paprika.v1.ListReleasesRequest
	11, // 9: paprika.v1.PaprikaService.ListStages:input_type -> paprika.v1.ListStagesRequest
	8,  // 10: paprika.v1.PaprikaService.ListPipelines:output_type -> paprika.v1.ListPipelinesResponse
	10, // 11: paprika.v1.PaprikaService.ListReleases:output_type -> paprika.v1.ListReleasesResponse
	12, // 12: paprika.v1.PaprikaService.ListStages:output_type -> paprika.v1.ListStagesResponse
	10, // [10:13] is the sub-list for method output_type
	7,  // [7:10] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_paprika_v1_api_proto_init() }
func file_paprika_v1_api_proto_init() {
	if File_paprika_v1_api_proto != nil {
		return
	}
	file_paprika_v1_api_proto_msgTypes[1].OneofWrappers = []any{}
	file_paprika_v1_api_proto_msgTypes[7].OneofWrappers = []any{}
	file_paprika_v1_api_proto_msgTypes[9].OneofWrappers = []any{}
	file_paprika_v1_api_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paprika_v1_api_proto_rawDesc), len(file_paprika_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paprika_v1_api_proto_goTypes,
		DependencyIndexes: file_paprika_v1_api_proto_depIdxs,
		MessageInfos:      file_paprika_v1_api_proto_msgTypes,
	}.Build()
	File_paprika_v1_api_proto = out.File
	file_paprika_v1_api_proto_goTypes = nil
	file_paprika_v1_api_proto_depIdxs = nil
}
