// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/internal/cache (interfaces: Getter,Setter,Deleter,Pinger,Closer,PrefixDeleter)
//
// Generated by this command:
//
//	mockgen -destination=mocks/cache.go -package=mocks -typed . Getter,Setter,Deleter,Pinger,Closer,PrefixDeleter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockGetter is a mock of Getter interface.
type MockGetter struct {
	ctrl     *gomock.Controller
	recorder *MockGetterMockRecorder
	isgomock struct{}
}

// MockGetterMockRecorder is the mock recorder for MockGetter.
type MockGetterMockRecorder struct {
	mock *MockGetter
}

// NewMockGetter creates a new mock instance.
func NewMockGetter(ctrl *gomock.Controller) *MockGetter {
	mock := &MockGetter{ctrl: ctrl}
	mock.recorder = &MockGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGetter) EXPECT() *MockGetterMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockGetter) Get(ctx context.Context, key string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockGetterMockRecorder) Get(ctx, key any) *MockGetterGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockGetter)(nil).Get), ctx, key)
	return &MockGetterGetCall{Call: call}
}

// MockGetterGetCall wrap *gomock.Call
type MockGetterGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockGetterGetCall) Return(arg0 []byte, arg1 error) *MockGetterGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockGetterGetCall) Do(f func(context.Context, string) ([]byte, error)) *MockGetterGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockGetterGetCall) DoAndReturn(f func(context.Context, string) ([]byte, error)) *MockGetterGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockSetter is a mock of Setter interface.
type MockSetter struct {
	ctrl     *gomock.Controller
	recorder *MockSetterMockRecorder
	isgomock struct{}
}

// MockSetterMockRecorder is the mock recorder for MockSetter.
type MockSetterMockRecorder struct {
	mock *MockSetter
}

// NewMockSetter creates a new mock instance.
func NewMockSetter(ctrl *gomock.Controller) *MockSetter {
	mock := &MockSetter{ctrl: ctrl}
	mock.recorder = &MockSetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSetter) EXPECT() *MockSetterMockRecorder {
	return m.recorder
}

// Set mocks base method.
func (m *MockSetter) Set(ctx context.Context, key string, value []byte, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockSetterMockRecorder) Set(ctx, key, value, ttl any) *MockSetterSetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockSetter)(nil).Set), ctx, key, value, ttl)
	return &MockSetterSetCall{Call: call}
}

// MockSetterSetCall wrap *gomock.Call
type MockSetterSetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockSetterSetCall) Return(arg0 error) *MockSetterSetCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockSetterSetCall) Do(f func(context.Context, string, []byte, time.Duration) error) *MockSetterSetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockSetterSetCall) DoAndReturn(f func(context.Context, string, []byte, time.Duration) error) *MockSetterSetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockDeleter is a mock of Deleter interface.
type MockDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockDeleterMockRecorder
	isgomock struct{}
}

// MockDeleterMockRecorder is the mock recorder for MockDeleter.
type MockDeleterMockRecorder struct {
	mock *MockDeleter
}

// NewMockDeleter creates a new mock instance.
func NewMockDeleter(ctrl *gomock.Controller) *MockDeleter {
	mock := &MockDeleter{ctrl: ctrl}
	mock.recorder = &MockDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeleter) EXPECT() *MockDeleterMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockDeleter) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDeleterMockRecorder) Delete(ctx, key any) *MockDeleterDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeleter)(nil).Delete), ctx, key)
	return &MockDeleterDeleteCall{Call: call}
}

// MockDeleterDeleteCall wrap *gomock.Call
type MockDeleterDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDeleterDeleteCall) Return(arg0 error) *MockDeleterDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDeleterDeleteCall) Do(f func(context.Context, string) error) *MockDeleterDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDeleterDeleteCall) DoAndReturn(f func(context.Context, string) error) *MockDeleterDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockPinger is a mock of Pinger interface.
type MockPinger struct {
	ctrl     *gomock.Controller
	recorder *MockPingerMockRecorder
	isgomock struct{}
}

// MockPingerMockRecorder is the mock recorder for MockPinger.
type MockPingerMockRecorder struct {
	mock *MockPinger
}

// NewMockPinger creates a new mock instance.
func NewMockPinger(ctrl *gomock.Controller) *MockPinger {
	mock := &MockPinger{ctrl: ctrl}
	mock.recorder = &MockPingerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPinger) EXPECT() *MockPingerMockRecorder {
	return m.recorder
}

// Ping mocks base method.
func (m *MockPinger) Ping(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ping", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ping indicates an expected call of Ping.
func (mr *MockPingerMockRecorder) Ping(ctx any) *MockPingerPingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockPinger)(nil).Ping), ctx)
	return &MockPingerPingCall{Call: call}
}

// MockPingerPingCall wrap *gomock.Call
type MockPingerPingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPingerPingCall) Return(arg0 error) *MockPingerPingCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPingerPingCall) Do(f func(context.Context) error) *MockPingerPingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPingerPingCall) DoAndReturn(f func(context.Context) error) *MockPingerPingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockCloser is a mock of Closer interface.
type MockCloser struct {
	ctrl     *gomock.Controller
	recorder *MockCloserMockRecorder
	isgomock struct{}
}

// MockCloserMockRecorder is the mock recorder for MockCloser.
type MockCloserMockRecorder struct {
	mock *MockCloser
}

// NewMockCloser creates a new mock instance.
func NewMockCloser(ctrl *gomock.Controller) *MockCloser {
	mock := &MockCloser{ctrl: ctrl}
	mock.recorder = &MockCloserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCloser) EXPECT() *MockCloserMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockCloser) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockCloserMockRecorder) Close() *MockCloserCloseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockCloser)(nil).Close))
	return &MockCloserCloseCall{Call: call}
}

// MockCloserCloseCall wrap *gomock.Call
type MockCloserCloseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockCloserCloseCall) Return(arg0 error) *MockCloserCloseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockCloserCloseCall) Do(f func() error) *MockCloserCloseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockCloserCloseCall) DoAndReturn(f func() error) *MockCloserCloseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockPrefixDeleter is a mock of PrefixDeleter interface.
type MockPrefixDeleter struct {
	ctrl     *gomock.Controller
	recorder *MockPrefixDeleterMockRecorder
	isgomock struct{}
}

// MockPrefixDeleterMockRecorder is the mock recorder for MockPrefixDeleter.
type MockPrefixDeleterMockRecorder struct {
	mock *MockPrefixDeleter
}

// NewMockPrefixDeleter creates a new mock instance.
func NewMockPrefixDeleter(ctrl *gomock.Controller) *MockPrefixDeleter {
	mock := &MockPrefixDeleter{ctrl: ctrl}
	mock.recorder = &MockPrefixDeleterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrefixDeleter) EXPECT() *MockPrefixDeleterMockRecorder {
	return m.recorder
}

// DeleteByPrefix mocks base method.
func (m *MockPrefixDeleter) DeleteByPrefix(ctx context.Context, prefix string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByPrefix", ctx, prefix)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByPrefix indicates an expected call of DeleteByPrefix.
func (mr *MockPrefixDeleterMockRecorder) DeleteByPrefix(ctx, prefix any) *MockPrefixDeleterDeleteByPrefixCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByPrefix", reflect.TypeOf((*MockPrefixDeleter)(nil).DeleteByPrefix), ctx, prefix)
	return &MockPrefixDeleterDeleteByPrefixCall{Call: call}
}

// MockPrefixDeleterDeleteByPrefixCall wrap *gomock.Call
type MockPrefixDeleterDeleteByPrefixCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPrefixDeleterDeleteByPrefixCall) Return(arg0 error) *MockPrefixDeleterDeleteByPrefixCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPrefixDeleterDeleteByPrefixCall) Do(f func(context.Context, string) error) *MockPrefixDeleterDeleteByPrefixCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPrefixDeleterDeleteByPrefixCall) DoAndReturn(f func(context.Context, string) error) *MockPrefixDeleterDeleteByPrefixCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
