{{- if .Values.repoServer.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "paprika.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: repo-server
    {{- range $k, $v := .Values.commonLabels }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  name: {{ include "paprika.resourceName" (dict "suffix" "repo-server" "context" $) }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.repoServer.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ports:
  - name: health
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: repo
    port: {{ .Values.repoServer.service.port }}
    protocol: TCP
    targetPort: 8082
  - name: metrics
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "paprika.name" . }}
    app.kubernetes.io/component: repo-server
  type: {{ .Values.repoServer.service.type }}
{{- end }}
