// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/source (interfaces: GitSourceResolver)
//
// Generated by this command:
//
//	mockgen -destination=mocks/git_source_resolver.go -package=mocks . GitSourceResolver
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	source "github.com/benebsworth/paprika/source"
	gomock "go.uber.org/mock/gomock"
)

// MockGitSourceResolver is a mock of GitSourceResolver interface.
type MockGitSourceResolver struct {
	ctrl     *gomock.Controller
	recorder *MockGitSourceResolverMockRecorder
	isgomock struct{}
}

// MockGitSourceResolverMockRecorder is the mock recorder for MockGitSourceResolver.
type MockGitSourceResolverMockRecorder struct {
	mock *MockGitSourceResolver
}

// NewMockGitSourceResolver creates a new mock instance.
func NewMockGitSourceResolver(ctrl *gomock.Controller) *MockGitSourceResolver {
	mock := &MockGitSourceResolver{ctrl: ctrl}
	mock.recorder = &MockGitSourceResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGitSourceResolver) EXPECT() *MockGitSourceResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockGitSourceResolver) Resolve(ctx context.Context) (*source.ResolveResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx)
	ret0, _ := ret[0].(*source.ResolveResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockGitSourceResolverMockRecorder) Resolve(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockGitSourceResolver)(nil).Resolve), ctx)
}
