// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/source (interfaces: OCISourceResolver)
//
// Generated by this command:
//
//	mockgen -destination=mocks/oci_source_resolver.go -package=mocks . OCISourceResolver
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	source "github.com/benebsworth/paprika/source"
	gomock "go.uber.org/mock/gomock"
)

// MockOCISourceResolver is a mock of OCISourceResolver interface.
type MockOCISourceResolver struct {
	ctrl     *gomock.Controller
	recorder *MockOCISourceResolverMockRecorder
	isgomock struct{}
}

// MockOCISourceResolverMockRecorder is the mock recorder for MockOCISourceResolver.
type MockOCISourceResolverMockRecorder struct {
	mock *MockOCISourceResolver
}

// NewMockOCISourceResolver creates a new mock instance.
func NewMockOCISourceResolver(ctrl *gomock.Controller) *MockOCISourceResolver {
	mock := &MockOCISourceResolver{ctrl: ctrl}
	mock.recorder = &MockOCISourceResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOCISourceResolver) EXPECT() *MockOCISourceResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockOCISourceResolver) Resolve(ctx context.Context) (*source.ResolveResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx)
	ret0, _ := ret[0].(*source.ResolveResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockOCISourceResolverMockRecorder) Resolve(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockOCISourceResolver)(nil).Resolve), ctx)
}
