---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipelines.paprika.io
  resources:
  - artifacts
  - pipelines
  - releases
  - stages
  - templates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pipelines.paprika.io
  resources:
  - artifacts/finalizers
  - pipelines/finalizers
  - releases/finalizers
  - stages/finalizers
  - templates/finalizers
  verbs:
  - update
- apiGroups:
  - pipelines.paprika.io
  resources:
  - artifacts/status
  - pipelines/status
  - releases/status
  - stages/status
  - templates/status
  verbs:
  - get
  - patch
  - update
