# This rule is not used by the project paprika itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over pipelines.paprika.io.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: paprika
    app.kubernetes.io/managed-by: kustomize
  name: stage-admin-role
rules:
- apiGroups:
  - pipelines.paprika.io
  resources:
  - stages
  verbs:
  - '*'
- apiGroups:
  - pipelines.paprika.io
  resources:
  - stages/status
  verbs:
  - get
