// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/analysis (interfaces: Analyzer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/analyzer.go -package=mocks . Analyzer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	analysis "github.com/benebsworth/paprika/analysis"
	v1alpha1 "github.com/benebsworth/paprika/api/pipelines/v1alpha1"
	gomock "go.uber.org/mock/gomock"
)

// MockAnalyzer is a mock of Analyzer interface.
type MockAnalyzer struct {
	ctrl     *gomock.Controller
	recorder *MockAnalyzerMockRecorder
	isgomock struct{}
}

// MockAnalyzerMockRecorder is the mock recorder for MockAnalyzer.
type MockAnalyzerMockRecorder struct {
	mock *MockAnalyzer
}

// NewMockAnalyzer creates a new mock instance.
func NewMockAnalyzer(ctrl *gomock.Controller) *MockAnalyzer {
	mock := &MockAnalyzer{ctrl: ctrl}
	mock.recorder = &MockAnalyzerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAnalyzer) EXPECT() *MockAnalyzerMockRecorder {
	return m.recorder
}

// RunChecks mocks base method.
func (m *MockAnalyzer) RunChecks(ctx context.Context, checks []v1alpha1.AnalysisCheck) []analysis.Result {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunChecks", ctx, checks)
	ret0, _ := ret[0].([]analysis.Result)
	return ret0
}

// RunChecks indicates an expected call of RunChecks.
func (mr *MockAnalyzerMockRecorder) RunChecks(ctx, checks any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunChecks", reflect.TypeOf((*MockAnalyzer)(nil).RunChecks), ctx, checks)
}
