replicaCount: 1

imagePullSecrets:
  - name: brandbrain-gar

secretEnv:
  existingSecret: brandbrain-api-env
  optional: false

workloadIdentity:
  enabled: true
  projectNumber: "976998755879"
  pool: vke-omega
  provider: omega
  serviceAccountEmail: brandbrain-backend@brandbrain-486909.iam.gserviceaccount.com

gateway:
  enabled: true
  parentRefs:
    - name: paprika
      namespace: envoy-gateway-system
  hostnames:
    - origin-vke.brandbrain.dev
    - api.brandbrain.dev
