replicaCount: 1

imagePullSecrets:
  - name: cuttlefish-gar

secretEnv:
  existingSecret: cuttlefish-controlplane-env
  optional: false

workloadIdentity:
  enabled: true
  projectNumber: "698099003913"
  pool: vke-omega
  provider: omega
  serviceAccountEmail: cf-controlplane@cuttlefish-d16cd.iam.gserviceaccount.com

gateway:
  enabled: true
  parentRefs:
    - name: paprika
      namespace: envoy-gateway-system
  hostnames:
    - origin-vke.cuttlefish.sh
    - api.cuttlefish.sh
