apiVersion: pipelines.paprika.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  namespace: paprika-e2e
  labels:
    app.kubernetes.io/name: demo-app
spec:
  source:
    type: git
    repoUrl: https://github.com/paprikacd/paprika.git
    revision: master
    path: charts/demo-app
    pollInterval: 60s
  stages:
    - name: dev
      ring: 1
      autoPromote: true
      canary:
        steps: [50, 100]
        intervalSeconds: 10
      parameters:
        replicaCount: "1"
        features.ingress.enabled: "false"
  strategy: Canary
  syncPolicy: Auto
  healthChecks:
    - name: stable-service-http
      httpProbe:
        url: http://demo-app-release-demo-app-stable.paprika-e2e.svc.cluster.local/
        timeout: 3
      expression: http.statusCode == 200
  onFailure:
    action: rollback
