replicaCount: 1

imagePullSecrets:
  - name: flaggr-gar

workloadIdentity:
  enabled: true
  projectNumber: "92803451840"
  pool: vke-omega
  provider: omega
  serviceAccountEmail: flaggr-grpc-sa@flaggr-478302.iam.gserviceaccount.com

gateway:
  enabled: true
  parentRefs:
    - name: paprika
      namespace: envoy-gateway-system
  hostnames:
    - origin-vke.flaggr.dev
    - api.flaggr.dev
