// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: paprika/v1/api.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/benebsworth/paprika/internal/api/paprika/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PaprikaServiceName is the fully-qualified name of the PaprikaService service.
	PaprikaServiceName = "paprika.v1.PaprikaService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PaprikaServiceListPipelinesProcedure is the fully-qualified name of the PaprikaService's
	// ListPipelines RPC.
	PaprikaServiceListPipelinesProcedure = "/paprika.v1.PaprikaService/ListPipelines"
	// PaprikaServiceListReleasesProcedure is the fully-qualified name of the PaprikaService's
	// ListReleases RPC.
	PaprikaServiceListReleasesProcedure = "/paprika.v1.PaprikaService/ListReleases"
	// PaprikaServiceListStagesProcedure is the fully-qualified name of the PaprikaService's ListStages
	// RPC.
	PaprikaServiceListStagesProcedure = "/paprika.v1.PaprikaService/ListStages"
	// PaprikaServiceListApplicationsProcedure is the fully-qualified name of the PaprikaService's
	// ListApplications RPC.
	PaprikaServiceListApplicationsProcedure = "/paprika.v1.PaprikaService/ListApplications"
	// PaprikaServiceListPoliciesProcedure is the fully-qualified name of the PaprikaService's
	// ListPolicies RPC.
	PaprikaServiceListPoliciesProcedure = "/paprika.v1.PaprikaService/ListPolicies"
	// PaprikaServiceGetApplicationProcedure is the fully-qualified name of the PaprikaService's
	// GetApplication RPC.
	PaprikaServiceGetApplicationProcedure = "/paprika.v1.PaprikaService/GetApplication"
	// PaprikaServiceSyncApplicationProcedure is the fully-qualified name of the PaprikaService's
	// SyncApplication RPC.
	PaprikaServiceSyncApplicationProcedure = "/paprika.v1.PaprikaService/SyncApplication"
	// PaprikaServiceApproveGateProcedure is the fully-qualified name of the PaprikaService's
	// ApproveGate RPC.
	PaprikaServiceApproveGateProcedure = "/paprika.v1.PaprikaService/ApproveGate"
	// PaprikaServiceResolveSourceProcedure is the fully-qualified name of the PaprikaService's
	// ResolveSource RPC.
	PaprikaServiceResolveSourceProcedure = "/paprika.v1.PaprikaService/ResolveSource"
	// PaprikaServiceRenderProcedure is the fully-qualified name of the PaprikaService's Render RPC.
	PaprikaServiceRenderProcedure = "/paprika.v1.PaprikaService/Render"
	// PaprikaServiceApplyBundleProcedure is the fully-qualified name of the PaprikaService's
	// ApplyBundle RPC.
	PaprikaServiceApplyBundleProcedure = "/paprika.v1.PaprikaService/ApplyBundle"
)

// PaprikaServiceClient is a client for the paprika.v1.PaprikaService service.
type PaprikaServiceClient interface {
	ListPipelines(context.Context, *connect.Request[v1.ListPipelinesRequest]) (*connect.Response[v1.ListPipelinesResponse], error)
	ListReleases(context.Context, *connect.Request[v1.ListReleasesRequest]) (*connect.Response[v1.ListReleasesResponse], error)
	ListStages(context.Context, *connect.Request[v1.ListStagesRequest]) (*connect.Response[v1.ListStagesResponse], error)
	ListApplications(context.Context, *connect.Request[v1.ListApplicationsRequest]) (*connect.Response[v1.ListApplicationsResponse], error)
	ListPolicies(context.Context, *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.ListPoliciesResponse], error)
	GetApplication(context.Context, *connect.Request[v1.GetApplicationRequest]) (*connect.Response[v1.GetApplicationResponse], error)
	SyncApplication(context.Context, *connect.Request[v1.SyncApplicationRequest]) (*connect.Response[v1.SyncApplicationResponse], error)
	ApproveGate(context.Context, *connect.Request[v1.ApproveGateRequest]) (*connect.Response[v1.ApproveGateResponse], error)
	ResolveSource(context.Context, *connect.Request[v1.ResolveSourceRequest]) (*connect.Response[v1.ResolveSourceResponse], error)
	Render(context.Context, *connect.Request[v1.RenderRequest]) (*connect.Response[v1.RenderResponse], error)
	ApplyBundle(context.Context, *connect.Request[v1.ApplyBundleRequest]) (*connect.Response[v1.ApplyBundleResponse], error)
}

// NewPaprikaServiceClient constructs a client for the paprika.v1.PaprikaService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPaprikaServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PaprikaServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	paprikaServiceMethods := v1.File_paprika_v1_api_proto.Services().ByName("PaprikaService").Methods()
	return &paprikaServiceClient{
		listPipelines: connect.NewClient[v1.ListPipelinesRequest, v1.ListPipelinesResponse](
			httpClient,
			baseURL+PaprikaServiceListPipelinesProcedure,
			connect.WithSchema(paprikaServiceMethods.ByName("ListPipelines")),
			connect.WithClientOptions(opts...),
		),
		listReleases: connect.NewClient[v1.ListReleasesRequest, v1.ListReleasesResponse](
			httpClient,
			baseURL+PaprikaServiceListReleasesProcedure,
			connect.WithSchema(paprikaServiceMethods.ByName("ListReleases")),
			connect.WithClientOptions(opts...),
		),
		listStages: connect.NewClient[v1.ListStagesRequest, v1.ListStagesResponse](
			httpClient,
			baseURL+PaprikaServiceListStagesProcedure,
			connect.WithSchema(paprikaServiceMethods.ByName("ListStages")),
			connect.WithClientOptions(opts...),
		),
		listApplications: connect.NewClient[v1.ListApplicationsRequest, v1.ListApplicationsResponse](
			httpClient,
			baseURL+PaprikaServiceListApplicationsProcedure,
			connect.WithSchema(paprikaServiceMethods.ByName("ListApplications")),
			connect.WithClientOptions(opts...),
		),
		listPolicies: connect.NewClient[v1.ListPoliciesRequest, v1.ListPoliciesResponse](
			httpClient,
			baseURL+PaprikaServiceListPoliciesProcedure,
			connect.WithSchema(paprikaServiceMethods.ByName("ListPolicies")),
			connect.WithClientOptions(opts...),
		),
		getApplication: connect.NewClient[v1.GetApplicationRequest, v1.GetApplicationResponse](
			httpClient,
			baseURL+PaprikaServiceGetApplicationProcedure,
			connect.WithSchema(paprikaServiceMethods.ByName("GetApplication")),
			connect.WithClientOptions(opts...),
		),
		syncApplication: connect.NewClient[v1.SyncApplicationRequest, v1.SyncApplicationResponse](
			httpClient,
			baseURL+PaprikaServiceSyncApplicationProcedure,
			connect.WithSchema(paprikaServiceMethods.ByName("SyncApplication")),
			connect.WithClientOptions(opts...),
		),
		approveGate: connect.NewClient[v1.ApproveGateRequest, v1.ApproveGateResponse](
			httpClient,
			baseURL+PaprikaServiceApproveGateProcedure,
			connect.WithSchema(paprikaServiceMethods.ByName("ApproveGate")),
			connect.WithClientOptions(opts...),
		),
		resolveSource: connect.NewClient[v1.ResolveSourceRequest, v1.ResolveSourceResponse](
			httpClient,
			baseURL+PaprikaServiceResolveSourceProcedure,
			connect.WithSchema(paprikaServiceMethods.ByName("ResolveSource")),
			connect.WithClientOptions(opts...),
		),
		render: connect.NewClient[v1.RenderRequest, v1.RenderResponse](
			httpClient,
			baseURL+PaprikaServiceRenderProcedure,
			connect.WithSchema(paprikaServiceMethods.ByName("Render")),
			connect.WithClientOptions(opts...),
		),
		applyBundle: connect.NewClient[v1.ApplyBundleRequest, v1.ApplyBundleResponse](
			httpClient,
			baseURL+PaprikaServiceApplyBundleProcedure,
			connect.WithSchema(paprikaServiceMethods.ByName("ApplyBundle")),
			connect.WithClientOptions(opts...),
		),
	}
}

// paprikaServiceClient implements PaprikaServiceClient.
type paprikaServiceClient struct {
	listPipelines    *connect.Client[v1.ListPipelinesRequest, v1.ListPipelinesResponse]
	listReleases     *connect.Client[v1.ListReleasesRequest, v1.ListReleasesResponse]
	listStages       *connect.Client[v1.ListStagesRequest, v1.ListStagesResponse]
	listApplications *connect.Client[v1.ListApplicationsRequest, v1.ListApplicationsResponse]
	listPolicies     *connect.Client[v1.ListPoliciesRequest, v1.ListPoliciesResponse]
	getApplication   *connect.Client[v1.GetApplicationRequest, v1.GetApplicationResponse]
	syncApplication  *connect.Client[v1.SyncApplicationRequest, v1.SyncApplicationResponse]
	approveGate      *connect.Client[v1.ApproveGateRequest, v1.ApproveGateResponse]
	resolveSource    *connect.Client[v1.ResolveSourceRequest, v1.ResolveSourceResponse]
	render           *connect.Client[v1.RenderRequest, v1.RenderResponse]
	applyBundle      *connect.Client[v1.ApplyBundleRequest, v1.ApplyBundleResponse]
}

// ListPipelines calls paprika.v1.PaprikaService.ListPipelines.
func (c *paprikaServiceClient) ListPipelines(ctx context.Context, req *connect.Request[v1.ListPipelinesRequest]) (*connect.Response[v1.ListPipelinesResponse], error) {
	return c.listPipelines.CallUnary(ctx, req)
}

// ListReleases calls paprika.v1.PaprikaService.ListReleases.
func (c *paprikaServiceClient) ListReleases(ctx context.Context, req *connect.Request[v1.ListReleasesRequest]) (*connect.Response[v1.ListReleasesResponse], error) {
	return c.listReleases.CallUnary(ctx, req)
}

// ListStages calls paprika.v1.PaprikaService.ListStages.
func (c *paprikaServiceClient) ListStages(ctx context.Context, req *connect.Request[v1.ListStagesRequest]) (*connect.Response[v1.ListStagesResponse], error) {
	return c.listStages.CallUnary(ctx, req)
}

// ListApplications calls paprika.v1.PaprikaService.ListApplications.
func (c *paprikaServiceClient) ListApplications(ctx context.Context, req *connect.Request[v1.ListApplicationsRequest]) (*connect.Response[v1.ListApplicationsResponse], error) {
	return c.listApplications.CallUnary(ctx, req)
}

// ListPolicies calls paprika.v1.PaprikaService.ListPolicies.
func (c *paprikaServiceClient) ListPolicies(ctx context.Context, req *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.ListPoliciesResponse], error) {
	return c.listPolicies.CallUnary(ctx, req)
}

// GetApplication calls paprika.v1.PaprikaService.GetApplication.
func (c *paprikaServiceClient) GetApplication(ctx context.Context, req *connect.Request[v1.GetApplicationRequest]) (*connect.Response[v1.GetApplicationResponse], error) {
	return c.getApplication.CallUnary(ctx, req)
}

// SyncApplication calls paprika.v1.PaprikaService.SyncApplication.
func (c *paprikaServiceClient) SyncApplication(ctx context.Context, req *connect.Request[v1.SyncApplicationRequest]) (*connect.Response[v1.SyncApplicationResponse], error) {
	return c.syncApplication.CallUnary(ctx, req)
}

// ApproveGate calls paprika.v1.PaprikaService.ApproveGate.
func (c *paprikaServiceClient) ApproveGate(ctx context.Context, req *connect.Request[v1.ApproveGateRequest]) (*connect.Response[v1.ApproveGateResponse], error) {
	return c.approveGate.CallUnary(ctx, req)
}

// ResolveSource calls paprika.v1.PaprikaService.ResolveSource.
func (c *paprikaServiceClient) ResolveSource(ctx context.Context, req *connect.Request[v1.ResolveSourceRequest]) (*connect.Response[v1.ResolveSourceResponse], error) {
	return c.resolveSource.CallUnary(ctx, req)
}

// Render calls paprika.v1.PaprikaService.Render.
func (c *paprikaServiceClient) Render(ctx context.Context, req *connect.Request[v1.RenderRequest]) (*connect.Response[v1.RenderResponse], error) {
	return c.render.CallUnary(ctx, req)
}

// ApplyBundle calls paprika.v1.PaprikaService.ApplyBundle.
func (c *paprikaServiceClient) ApplyBundle(ctx context.Context, req *connect.Request[v1.ApplyBundleRequest]) (*connect.Response[v1.ApplyBundleResponse], error) {
	return c.applyBundle.CallUnary(ctx, req)
}

// PaprikaServiceHandler is an implementation of the paprika.v1.PaprikaService service.
type PaprikaServiceHandler interface {
	ListPipelines(context.Context, *connect.Request[v1.ListPipelinesRequest]) (*connect.Response[v1.ListPipelinesResponse], error)
	ListReleases(context.Context, *connect.Request[v1.ListReleasesRequest]) (*connect.Response[v1.ListReleasesResponse], error)
	ListStages(context.Context, *connect.Request[v1.ListStagesRequest]) (*connect.Response[v1.ListStagesResponse], error)
	ListApplications(context.Context, *connect.Request[v1.ListApplicationsRequest]) (*connect.Response[v1.ListApplicationsResponse], error)
	ListPolicies(context.Context, *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.ListPoliciesResponse], error)
	GetApplication(context.Context, *connect.Request[v1.GetApplicationRequest]) (*connect.Response[v1.GetApplicationResponse], error)
	SyncApplication(context.Context, *connect.Request[v1.SyncApplicationRequest]) (*connect.Response[v1.SyncApplicationResponse], error)
	ApproveGate(context.Context, *connect.Request[v1.ApproveGateRequest]) (*connect.Response[v1.ApproveGateResponse], error)
	ResolveSource(context.Context, *connect.Request[v1.ResolveSourceRequest]) (*connect.Response[v1.ResolveSourceResponse], error)
	Render(context.Context, *connect.Request[v1.RenderRequest]) (*connect.Response[v1.RenderResponse], error)
	ApplyBundle(context.Context, *connect.Request[v1.ApplyBundleRequest]) (*connect.Response[v1.ApplyBundleResponse], error)
}

// NewPaprikaServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPaprikaServiceHandler(svc PaprikaServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	paprikaServiceMethods := v1.File_paprika_v1_api_proto.Services().ByName("PaprikaService").Methods()
	paprikaServiceListPipelinesHandler := connect.NewUnaryHandler(
		PaprikaServiceListPipelinesProcedure,
		svc.ListPipelines,
		connect.WithSchema(paprikaServiceMethods.ByName("ListPipelines")),
		connect.WithHandlerOptions(opts...),
	)
	paprikaServiceListReleasesHandler := connect.NewUnaryHandler(
		PaprikaServiceListReleasesProcedure,
		svc.ListReleases,
		connect.WithSchema(paprikaServiceMethods.ByName("ListReleases")),
		connect.WithHandlerOptions(opts...),
	)
	paprikaServiceListStagesHandler := connect.NewUnaryHandler(
		PaprikaServiceListStagesProcedure,
		svc.ListStages,
		connect.WithSchema(paprikaServiceMethods.ByName("ListStages")),
		connect.WithHandlerOptions(opts...),
	)
	paprikaServiceListApplicationsHandler := connect.NewUnaryHandler(
		PaprikaServiceListApplicationsProcedure,
		svc.ListApplications,
		connect.WithSchema(paprikaServiceMethods.ByName("ListApplications")),
		connect.WithHandlerOptions(opts...),
	)
	paprikaServiceListPoliciesHandler := connect.NewUnaryHandler(
		PaprikaServiceListPoliciesProcedure,
		svc.ListPolicies,
		connect.WithSchema(paprikaServiceMethods.ByName("ListPolicies")),
		connect.WithHandlerOptions(opts...),
	)
	paprikaServiceGetApplicationHandler := connect.NewUnaryHandler(
		PaprikaServiceGetApplicationProcedure,
		svc.GetApplication,
		connect.WithSchema(paprikaServiceMethods.ByName("GetApplication")),
		connect.WithHandlerOptions(opts...),
	)
	paprikaServiceSyncApplicationHandler := connect.NewUnaryHandler(
		PaprikaServiceSyncApplicationProcedure,
		svc.SyncApplication,
		connect.WithSchema(paprikaServiceMethods.ByName("SyncApplication")),
		connect.WithHandlerOptions(opts...),
	)
	paprikaServiceApproveGateHandler := connect.NewUnaryHandler(
		PaprikaServiceApproveGateProcedure,
		svc.ApproveGate,
		connect.WithSchema(paprikaServiceMethods.ByName("ApproveGate")),
		connect.WithHandlerOptions(opts...),
	)
	paprikaServiceResolveSourceHandler := connect.NewUnaryHandler(
		PaprikaServiceResolveSourceProcedure,
		svc.ResolveSource,
		connect.WithSchema(paprikaServiceMethods.ByName("ResolveSource")),
		connect.WithHandlerOptions(opts...),
	)
	paprikaServiceRenderHandler := connect.NewUnaryHandler(
		PaprikaServiceRenderProcedure,
		svc.Render,
		connect.WithSchema(paprikaServiceMethods.ByName("Render")),
		connect.WithHandlerOptions(opts...),
	)
	paprikaServiceApplyBundleHandler := connect.NewUnaryHandler(
		PaprikaServiceApplyBundleProcedure,
		svc.ApplyBundle,
		connect.WithSchema(paprikaServiceMethods.ByName("ApplyBundle")),
		connect.WithHandlerOptions(opts...),
	)
	return "/paprika.v1.PaprikaService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PaprikaServiceListPipelinesProcedure:
			paprikaServiceListPipelinesHandler.ServeHTTP(w, r)
		case PaprikaServiceListReleasesProcedure:
			paprikaServiceListReleasesHandler.ServeHTTP(w, r)
		case PaprikaServiceListStagesProcedure:
			paprikaServiceListStagesHandler.ServeHTTP(w, r)
		case PaprikaServiceListApplicationsProcedure:
			paprikaServiceListApplicationsHandler.ServeHTTP(w, r)
		case PaprikaServiceListPoliciesProcedure:
			paprikaServiceListPoliciesHandler.ServeHTTP(w, r)
		case PaprikaServiceGetApplicationProcedure:
			paprikaServiceGetApplicationHandler.ServeHTTP(w, r)
		case PaprikaServiceSyncApplicationProcedure:
			paprikaServiceSyncApplicationHandler.ServeHTTP(w, r)
		case PaprikaServiceApproveGateProcedure:
			paprikaServiceApproveGateHandler.ServeHTTP(w, r)
		case PaprikaServiceResolveSourceProcedure:
			paprikaServiceResolveSourceHandler.ServeHTTP(w, r)
		case PaprikaServiceRenderProcedure:
			paprikaServiceRenderHandler.ServeHTTP(w, r)
		case PaprikaServiceApplyBundleProcedure:
			paprikaServiceApplyBundleHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPaprikaServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPaprikaServiceHandler struct{}

func (UnimplementedPaprikaServiceHandler) ListPipelines(context.Context, *connect.Request[v1.ListPipelinesRequest]) (*connect.Response[v1.ListPipelinesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paprika.v1.PaprikaService.ListPipelines is not implemented"))
}

func (UnimplementedPaprikaServiceHandler) ListReleases(context.Context, *connect.Request[v1.ListReleasesRequest]) (*connect.Response[v1.ListReleasesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paprika.v1.PaprikaService.ListReleases is not implemented"))
}

func (UnimplementedPaprikaServiceHandler) ListStages(context.Context, *connect.Request[v1.ListStagesRequest]) (*connect.Response[v1.ListStagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paprika.v1.PaprikaService.ListStages is not implemented"))
}

func (UnimplementedPaprikaServiceHandler) ListApplications(context.Context, *connect.Request[v1.ListApplicationsRequest]) (*connect.Response[v1.ListApplicationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paprika.v1.PaprikaService.ListApplications is not implemented"))
}

func (UnimplementedPaprikaServiceHandler) ListPolicies(context.Context, *connect.Request[v1.ListPoliciesRequest]) (*connect.Response[v1.ListPoliciesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paprika.v1.PaprikaService.ListPolicies is not implemented"))
}

func (UnimplementedPaprikaServiceHandler) GetApplication(context.Context, *connect.Request[v1.GetApplicationRequest]) (*connect.Response[v1.GetApplicationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paprika.v1.PaprikaService.GetApplication is not implemented"))
}

func (UnimplementedPaprikaServiceHandler) SyncApplication(context.Context, *connect.Request[v1.SyncApplicationRequest]) (*connect.Response[v1.SyncApplicationResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paprika.v1.PaprikaService.SyncApplication is not implemented"))
}

func (UnimplementedPaprikaServiceHandler) ApproveGate(context.Context, *connect.Request[v1.ApproveGateRequest]) (*connect.Response[v1.ApproveGateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paprika.v1.PaprikaService.ApproveGate is not implemented"))
}

func (UnimplementedPaprikaServiceHandler) ResolveSource(context.Context, *connect.Request[v1.ResolveSourceRequest]) (*connect.Response[v1.ResolveSourceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paprika.v1.PaprikaService.ResolveSource is not implemented"))
}

func (UnimplementedPaprikaServiceHandler) Render(context.Context, *connect.Request[v1.RenderRequest]) (*connect.Response[v1.RenderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paprika.v1.PaprikaService.Render is not implemented"))
}

func (UnimplementedPaprikaServiceHandler) ApplyBundle(context.Context, *connect.Request[v1.ApplyBundleRequest]) (*connect.Response[v1.ApplyBundleResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paprika.v1.PaprikaService.ApplyBundle is not implemented"))
}
