// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: paprika/v1/api.proto

package v1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/benebsworth/paprika/internal/api/paprika/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PaprikaServiceName is the fully-qualified name of the PaprikaService service.
	PaprikaServiceName = "paprika.v1.PaprikaService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PaprikaServiceListPipelinesProcedure is the fully-qualified name of the PaprikaService's
	// ListPipelines RPC.
	PaprikaServiceListPipelinesProcedure = "/paprika.v1.PaprikaService/ListPipelines"
	// PaprikaServiceListReleasesProcedure is the fully-qualified name of the PaprikaService's
	// ListReleases RPC.
	PaprikaServiceListReleasesProcedure = "/paprika.v1.PaprikaService/ListReleases"
	// PaprikaServiceListStagesProcedure is the fully-qualified name of the PaprikaService's ListStages
	// RPC.
	PaprikaServiceListStagesProcedure = "/paprika.v1.PaprikaService/ListStages"
)

// PaprikaServiceClient is a client for the paprika.v1.PaprikaService service.
type PaprikaServiceClient interface {
	ListPipelines(context.Context, *connect.Request[v1.ListPipelinesRequest]) (*connect.Response[v1.ListPipelinesResponse], error)
	ListReleases(context.Context, *connect.Request[v1.ListReleasesRequest]) (*connect.Response[v1.ListReleasesResponse], error)
	ListStages(context.Context, *connect.Request[v1.ListStagesRequest]) (*connect.Response[v1.ListStagesResponse], error)
}

// NewPaprikaServiceClient constructs a client for the paprika.v1.PaprikaService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPaprikaServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PaprikaServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	paprikaServiceMethods := v1.File_paprika_v1_api_proto.Services().ByName("PaprikaService").Methods()
	return &paprikaServiceClient{
		listPipelines: connect.NewClient[v1.ListPipelinesRequest, v1.ListPipelinesResponse](
			httpClient,
			baseURL+PaprikaServiceListPipelinesProcedure,
			connect.WithSchema(paprikaServiceMethods.ByName("ListPipelines")),
			connect.WithClientOptions(opts...),
		),
		listReleases: connect.NewClient[v1.ListReleasesRequest, v1.ListReleasesResponse](
			httpClient,
			baseURL+PaprikaServiceListReleasesProcedure,
			connect.WithSchema(paprikaServiceMethods.ByName("ListReleases")),
			connect.WithClientOptions(opts...),
		),
		listStages: connect.NewClient[v1.ListStagesRequest, v1.ListStagesResponse](
			httpClient,
			baseURL+PaprikaServiceListStagesProcedure,
			connect.WithSchema(paprikaServiceMethods.ByName("ListStages")),
			connect.WithClientOptions(opts...),
		),
	}
}

// paprikaServiceClient implements PaprikaServiceClient.
type paprikaServiceClient struct {
	listPipelines *connect.Client[v1.ListPipelinesRequest, v1.ListPipelinesResponse]
	listReleases  *connect.Client[v1.ListReleasesRequest, v1.ListReleasesResponse]
	listStages    *connect.Client[v1.ListStagesRequest, v1.ListStagesResponse]
}

// ListPipelines calls paprika.v1.PaprikaService.ListPipelines.
func (c *paprikaServiceClient) ListPipelines(ctx context.Context, req *connect.Request[v1.ListPipelinesRequest]) (*connect.Response[v1.ListPipelinesResponse], error) {
	return c.listPipelines.CallUnary(ctx, req)
}

// ListReleases calls paprika.v1.PaprikaService.ListReleases.
func (c *paprikaServiceClient) ListReleases(ctx context.Context, req *connect.Request[v1.ListReleasesRequest]) (*connect.Response[v1.ListReleasesResponse], error) {
	return c.listReleases.CallUnary(ctx, req)
}

// ListStages calls paprika.v1.PaprikaService.ListStages.
func (c *paprikaServiceClient) ListStages(ctx context.Context, req *connect.Request[v1.ListStagesRequest]) (*connect.Response[v1.ListStagesResponse], error) {
	return c.listStages.CallUnary(ctx, req)
}

// PaprikaServiceHandler is an implementation of the paprika.v1.PaprikaService service.
type PaprikaServiceHandler interface {
	ListPipelines(context.Context, *connect.Request[v1.ListPipelinesRequest]) (*connect.Response[v1.ListPipelinesResponse], error)
	ListReleases(context.Context, *connect.Request[v1.ListReleasesRequest]) (*connect.Response[v1.ListReleasesResponse], error)
	ListStages(context.Context, *connect.Request[v1.ListStagesRequest]) (*connect.Response[v1.ListStagesResponse], error)
}

// NewPaprikaServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPaprikaServiceHandler(svc PaprikaServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	paprikaServiceMethods := v1.File_paprika_v1_api_proto.Services().ByName("PaprikaService").Methods()
	paprikaServiceListPipelinesHandler := connect.NewUnaryHandler(
		PaprikaServiceListPipelinesProcedure,
		svc.ListPipelines,
		connect.WithSchema(paprikaServiceMethods.ByName("ListPipelines")),
		connect.WithHandlerOptions(opts...),
	)
	paprikaServiceListReleasesHandler := connect.NewUnaryHandler(
		PaprikaServiceListReleasesProcedure,
		svc.ListReleases,
		connect.WithSchema(paprikaServiceMethods.ByName("ListReleases")),
		connect.WithHandlerOptions(opts...),
	)
	paprikaServiceListStagesHandler := connect.NewUnaryHandler(
		PaprikaServiceListStagesProcedure,
		svc.ListStages,
		connect.WithSchema(paprikaServiceMethods.ByName("ListStages")),
		connect.WithHandlerOptions(opts...),
	)
	return "/paprika.v1.PaprikaService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PaprikaServiceListPipelinesProcedure:
			paprikaServiceListPipelinesHandler.ServeHTTP(w, r)
		case PaprikaServiceListReleasesProcedure:
			paprikaServiceListReleasesHandler.ServeHTTP(w, r)
		case PaprikaServiceListStagesProcedure:
			paprikaServiceListStagesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPaprikaServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPaprikaServiceHandler struct{}

func (UnimplementedPaprikaServiceHandler) ListPipelines(context.Context, *connect.Request[v1.ListPipelinesRequest]) (*connect.Response[v1.ListPipelinesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paprika.v1.PaprikaService.ListPipelines is not implemented"))
}

func (UnimplementedPaprikaServiceHandler) ListReleases(context.Context, *connect.Request[v1.ListReleasesRequest]) (*connect.Response[v1.ListReleasesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paprika.v1.PaprikaService.ListReleases is not implemented"))
}

func (UnimplementedPaprikaServiceHandler) ListStages(context.Context, *connect.Request[v1.ListStagesRequest]) (*connect.Response[v1.ListStagesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paprika.v1.PaprikaService.ListStages is not implemented"))
}
