## Append samples of your project ##
resources:
- pipelines_v1alpha1_pipeline.yaml
- pipelines_v1alpha1_stage.yaml
- pipelines_v1alpha1_release.yaml
- pipelines_v1alpha1_template.yaml
- pipelines_v1alpha1_artifact.yaml
- pipelines_v1alpha1_application.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
