apiVersion: pipelines.paprika.io/v1alpha1
kind: ConftestPolicy
metadata:
  labels:
    app.kubernetes.io/name: paprika
    app.kubernetes.io/managed-by: kustomize
  name: conftestpolicy-sample
spec:
  # TODO(user): Add fields here
