apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects.yaml
  - clusters.yaml
  - applications.yaml
  - stages.yaml
  - releases.yaml
  - rollouts.yaml
  - pipelines.yaml
