// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/internal/traffic (interfaces: WeightRouter,HeaderRouter,MirrorRouter,Provider)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_traffic.go -package=mocks -typed . WeightRouter,HeaderRouter,MirrorRouter,Provider
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWeightRouter is a mock of WeightRouter interface.
type MockWeightRouter struct {
	ctrl     *gomock.Controller
	recorder *MockWeightRouterMockRecorder
	isgomock struct{}
}

// MockWeightRouterMockRecorder is the mock recorder for MockWeightRouter.
type MockWeightRouterMockRecorder struct {
	mock *MockWeightRouter
}

// NewMockWeightRouter creates a new mock instance.
func NewMockWeightRouter(ctrl *gomock.Controller) *MockWeightRouter {
	mock := &MockWeightRouter{ctrl: ctrl}
	mock.recorder = &MockWeightRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWeightRouter) EXPECT() *MockWeightRouterMockRecorder {
	return m.recorder
}

// RemoveCanary mocks base method.
func (m *MockWeightRouter) RemoveCanary(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveCanary", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveCanary indicates an expected call of RemoveCanary.
func (mr *MockWeightRouterMockRecorder) RemoveCanary(ctx any) *MockWeightRouterRemoveCanaryCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveCanary", reflect.TypeOf((*MockWeightRouter)(nil).RemoveCanary), ctx)
	return &MockWeightRouterRemoveCanaryCall{Call: call}
}

// MockWeightRouterRemoveCanaryCall wrap *gomock.Call
type MockWeightRouterRemoveCanaryCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWeightRouterRemoveCanaryCall) Return(arg0 error) *MockWeightRouterRemoveCanaryCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWeightRouterRemoveCanaryCall) Do(f func(context.Context) error) *MockWeightRouterRemoveCanaryCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWeightRouterRemoveCanaryCall) DoAndReturn(f func(context.Context) error) *MockWeightRouterRemoveCanaryCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetWeight mocks base method.
func (m *MockWeightRouter) SetWeight(ctx context.Context, weight int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWeight", ctx, weight)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWeight indicates an expected call of SetWeight.
func (mr *MockWeightRouterMockRecorder) SetWeight(ctx, weight any) *MockWeightRouterSetWeightCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWeight", reflect.TypeOf((*MockWeightRouter)(nil).SetWeight), ctx, weight)
	return &MockWeightRouterSetWeightCall{Call: call}
}

// MockWeightRouterSetWeightCall wrap *gomock.Call
type MockWeightRouterSetWeightCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockWeightRouterSetWeightCall) Return(arg0 error) *MockWeightRouterSetWeightCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockWeightRouterSetWeightCall) Do(f func(context.Context, int32) error) *MockWeightRouterSetWeightCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockWeightRouterSetWeightCall) DoAndReturn(f func(context.Context, int32) error) *MockWeightRouterSetWeightCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockHeaderRouter is a mock of HeaderRouter interface.
type MockHeaderRouter struct {
	ctrl     *gomock.Controller
	recorder *MockHeaderRouterMockRecorder
	isgomock struct{}
}

// MockHeaderRouterMockRecorder is the mock recorder for MockHeaderRouter.
type MockHeaderRouterMockRecorder struct {
	mock *MockHeaderRouter
}

// NewMockHeaderRouter creates a new mock instance.
func NewMockHeaderRouter(ctrl *gomock.Controller) *MockHeaderRouter {
	mock := &MockHeaderRouter{ctrl: ctrl}
	mock.recorder = &MockHeaderRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHeaderRouter) EXPECT() *MockHeaderRouterMockRecorder {
	return m.recorder
}

// RemoveHeaderRoute mocks base method.
func (m *MockHeaderRouter) RemoveHeaderRoute(ctx context.Context, header string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveHeaderRoute", ctx, header)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveHeaderRoute indicates an expected call of RemoveHeaderRoute.
func (mr *MockHeaderRouterMockRecorder) RemoveHeaderRoute(ctx, header any) *MockHeaderRouterRemoveHeaderRouteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveHeaderRoute", reflect.TypeOf((*MockHeaderRouter)(nil).RemoveHeaderRoute), ctx, header)
	return &MockHeaderRouterRemoveHeaderRouteCall{Call: call}
}

// MockHeaderRouterRemoveHeaderRouteCall wrap *gomock.Call
type MockHeaderRouterRemoveHeaderRouteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHeaderRouterRemoveHeaderRouteCall) Return(arg0 error) *MockHeaderRouterRemoveHeaderRouteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHeaderRouterRemoveHeaderRouteCall) Do(f func(context.Context, string) error) *MockHeaderRouterRemoveHeaderRouteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHeaderRouterRemoveHeaderRouteCall) DoAndReturn(f func(context.Context, string) error) *MockHeaderRouterRemoveHeaderRouteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetHeaderRoute mocks base method.
func (m *MockHeaderRouter) SetHeaderRoute(ctx context.Context, header, value, service string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetHeaderRoute", ctx, header, value, service)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetHeaderRoute indicates an expected call of SetHeaderRoute.
func (mr *MockHeaderRouterMockRecorder) SetHeaderRoute(ctx, header, value, service any) *MockHeaderRouterSetHeaderRouteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetHeaderRoute", reflect.TypeOf((*MockHeaderRouter)(nil).SetHeaderRoute), ctx, header, value, service)
	return &MockHeaderRouterSetHeaderRouteCall{Call: call}
}

// MockHeaderRouterSetHeaderRouteCall wrap *gomock.Call
type MockHeaderRouterSetHeaderRouteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockHeaderRouterSetHeaderRouteCall) Return(arg0 error) *MockHeaderRouterSetHeaderRouteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockHeaderRouterSetHeaderRouteCall) Do(f func(context.Context, string, string, string) error) *MockHeaderRouterSetHeaderRouteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockHeaderRouterSetHeaderRouteCall) DoAndReturn(f func(context.Context, string, string, string) error) *MockHeaderRouterSetHeaderRouteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockMirrorRouter is a mock of MirrorRouter interface.
type MockMirrorRouter struct {
	ctrl     *gomock.Controller
	recorder *MockMirrorRouterMockRecorder
	isgomock struct{}
}

// MockMirrorRouterMockRecorder is the mock recorder for MockMirrorRouter.
type MockMirrorRouterMockRecorder struct {
	mock *MockMirrorRouter
}

// NewMockMirrorRouter creates a new mock instance.
func NewMockMirrorRouter(ctrl *gomock.Controller) *MockMirrorRouter {
	mock := &MockMirrorRouter{ctrl: ctrl}
	mock.recorder = &MockMirrorRouterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMirrorRouter) EXPECT() *MockMirrorRouterMockRecorder {
	return m.recorder
}

// RemoveMirror mocks base method.
func (m *MockMirrorRouter) RemoveMirror(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveMirror", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveMirror indicates an expected call of RemoveMirror.
func (mr *MockMirrorRouterMockRecorder) RemoveMirror(ctx any) *MockMirrorRouterRemoveMirrorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveMirror", reflect.TypeOf((*MockMirrorRouter)(nil).RemoveMirror), ctx)
	return &MockMirrorRouterRemoveMirrorCall{Call: call}
}

// MockMirrorRouterRemoveMirrorCall wrap *gomock.Call
type MockMirrorRouterRemoveMirrorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMirrorRouterRemoveMirrorCall) Return(arg0 error) *MockMirrorRouterRemoveMirrorCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMirrorRouterRemoveMirrorCall) Do(f func(context.Context) error) *MockMirrorRouterRemoveMirrorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMirrorRouterRemoveMirrorCall) DoAndReturn(f func(context.Context) error) *MockMirrorRouterRemoveMirrorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SetMirror mocks base method.
func (m *MockMirrorRouter) SetMirror(ctx context.Context, percent int32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetMirror", ctx, percent)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetMirror indicates an expected call of SetMirror.
func (mr *MockMirrorRouterMockRecorder) SetMirror(ctx, percent any) *MockMirrorRouterSetMirrorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMirror", reflect.TypeOf((*MockMirrorRouter)(nil).SetMirror), ctx, percent)
	return &MockMirrorRouterSetMirrorCall{Call: call}
}

// MockMirrorRouterSetMirrorCall wrap *gomock.Call
type MockMirrorRouterSetMirrorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMirrorRouterSetMirrorCall) Return(arg0 error) *MockMirrorRouterSetMirrorCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMirrorRouterSetMirrorCall) Do(f func(context.Context, int32) error) *MockMirrorRouterSetMirrorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMirrorRouterSetMirrorCall) DoAndReturn(f func(context.Context, int32) error) *MockMirrorRouterSetMirrorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
	isgomock struct{}
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// Type mocks base method.
func (m *MockProvider) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockProviderMockRecorder) Type() *MockProviderTypeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockProvider)(nil).Type))
	return &MockProviderTypeCall{Call: call}
}

// MockProviderTypeCall wrap *gomock.Call
type MockProviderTypeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockProviderTypeCall) Return(arg0 string) *MockProviderTypeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockProviderTypeCall) Do(f func() string) *MockProviderTypeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockProviderTypeCall) DoAndReturn(f func() string) *MockProviderTypeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
