// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/gates (interfaces: GateExecutor)
//
// Generated by this command:
//
//	mockgen -destination=mocks/gate_executor.go -package=mocks . GateExecutor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gates "github.com/benebsworth/paprika/gates"
	gomock "go.uber.org/mock/gomock"
)

// MockGateExecutor is a mock of GateExecutor interface.
type MockGateExecutor struct {
	ctrl     *gomock.Controller
	recorder *MockGateExecutorMockRecorder
	isgomock struct{}
}

// MockGateExecutorMockRecorder is the mock recorder for MockGateExecutor.
type MockGateExecutorMockRecorder struct {
	mock *MockGateExecutor
}

// NewMockGateExecutor creates a new mock instance.
func NewMockGateExecutor(ctrl *gomock.Controller) *MockGateExecutor {
	mock := &MockGateExecutor{ctrl: ctrl}
	mock.recorder = &MockGateExecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockGateExecutor) EXPECT() *MockGateExecutorMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockGateExecutor) Execute(ctx context.Context, config gates.GateConfig) gates.GateResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, config)
	ret0, _ := ret[0].(gates.GateResult)
	return ret0
}

// Execute indicates an expected call of Execute.
func (mr *MockGateExecutorMockRecorder) Execute(ctx, config any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockGateExecutor)(nil).Execute), ctx, config)
}
