apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: system
spec:
  template:
    spec:
      containers:
      - name: manager
        args:
        - --leader-elect
        - --metrics-bind-address=:8443
        - --health-probe-bind-address=:8081
        - --webhook-cert-path=/tmp/k8s-webhook-server/serving-certs
        - --controllers-only
        ports:
        - $patch: replace
        - containerPort: 8081
          name: health
          protocol: TCP
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
