# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/pipelines.paprika.io_pipelines.yaml
- bases/pipelines.paprika.io_stages.yaml
- bases/pipelines.paprika.io_releases.yaml
- bases/pipelines.paprika.io_templates.yaml
- bases/pipelines.paprika.io_artifacts.yaml
- bases/pipelines.paprika.io_applications.yaml
- bases/pipelines.paprika.io_notificationconfigs.yaml
- bases/clusters.paprika.io_clusters.yaml
- bases/core.paprika.io_appprojects.yaml
- bases/core.paprika.io_repositories.yaml
- bases/policy.paprika.io_policies.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
