// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/engine (interfaces: SourceResolver)
//
// Generated by this command:
//
//	mockgen -destination=mocks/source_resolver.go -package=mocks . SourceResolver
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	source "github.com/benebsworth/paprika/source"
	gomock "go.uber.org/mock/gomock"
)

// MockSourceResolver is a mock of SourceResolver interface.
type MockSourceResolver struct {
	ctrl     *gomock.Controller
	recorder *MockSourceResolverMockRecorder
	isgomock struct{}
}

// MockSourceResolverMockRecorder is the mock recorder for MockSourceResolver.
type MockSourceResolverMockRecorder struct {
	mock *MockSourceResolver
}

// NewMockSourceResolver creates a new mock instance.
func NewMockSourceResolver(ctrl *gomock.Controller) *MockSourceResolver {
	mock := &MockSourceResolver{ctrl: ctrl}
	mock.recorder = &MockSourceResolverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSourceResolver) EXPECT() *MockSourceResolverMockRecorder {
	return m.recorder
}

// Resolve mocks base method.
func (m *MockSourceResolver) Resolve(ctx context.Context) (*source.ResolveResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", ctx)
	ret0, _ := ret[0].(*source.ResolveResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Resolve indicates an expected call of Resolve.
func (mr *MockSourceResolverMockRecorder) Resolve(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockSourceResolver)(nil).Resolve), ctx)
}
