// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/engine (interfaces: TemplateRenderer)
//
// Generated by this command:
//
//	mockgen -destination=mocks/template_renderer.go -package=mocks . TemplateRenderer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/benebsworth/paprika/api/pipelines/v1alpha1"
	source "github.com/benebsworth/paprika/source"
	gomock "go.uber.org/mock/gomock"
)

// MockTemplateRenderer is a mock of TemplateRenderer interface.
type MockTemplateRenderer struct {
	ctrl     *gomock.Controller
	recorder *MockTemplateRendererMockRecorder
	isgomock struct{}
}

// MockTemplateRendererMockRecorder is the mock recorder for MockTemplateRenderer.
type MockTemplateRendererMockRecorder struct {
	mock *MockTemplateRenderer
}

// NewMockTemplateRenderer creates a new mock instance.
func NewMockTemplateRenderer(ctrl *gomock.Controller) *MockTemplateRenderer {
	mock := &MockTemplateRenderer{ctrl: ctrl}
	mock.recorder = &MockTemplateRendererMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTemplateRenderer) EXPECT() *MockTemplateRendererMockRecorder {
	return m.recorder
}

// Render mocks base method.
func (m *MockTemplateRenderer) Render(ctx context.Context, tmpl *v1alpha1.Template, params map[string]string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", ctx, tmpl, params)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Render indicates an expected call of Render.
func (mr *MockTemplateRendererMockRecorder) Render(ctx, tmpl, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockTemplateRenderer)(nil).Render), ctx, tmpl, params)
}

// RenderAll mocks base method.
func (m *MockTemplateRenderer) RenderAll(ctx context.Context, templates []v1alpha1.Template, params map[string]string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderAll", ctx, templates, params)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderAll indicates an expected call of RenderAll.
func (mr *MockTemplateRendererMockRecorder) RenderAll(ctx, templates, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderAll", reflect.TypeOf((*MockTemplateRenderer)(nil).RenderAll), ctx, templates, params)
}

// RenderHelmChart mocks base method.
func (m *MockTemplateRenderer) RenderHelmChart(ctx context.Context, chartName, chartRepo, chartVersion string, values map[string]string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RenderHelmChart", ctx, chartName, chartRepo, chartVersion, values)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RenderHelmChart indicates an expected call of RenderHelmChart.
func (mr *MockTemplateRendererMockRecorder) RenderHelmChart(ctx, chartName, chartRepo, chartVersion, values any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RenderHelmChart", reflect.TypeOf((*MockTemplateRenderer)(nil).RenderHelmChart), ctx, chartName, chartRepo, chartVersion, values)
}

// ResolveSource mocks base method.
func (m *MockTemplateRenderer) ResolveSource(ctx context.Context, tmpl *v1alpha1.Template) (*source.ResolveResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ResolveSource", ctx, tmpl)
	ret0, _ := ret[0].(*source.ResolveResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ResolveSource indicates an expected call of ResolveSource.
func (mr *MockTemplateRendererMockRecorder) ResolveSource(ctx, tmpl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ResolveSource", reflect.TypeOf((*MockTemplateRenderer)(nil).ResolveSource), ctx, tmpl)
}
