// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/health (interfaces: HealthEvaluator)
//
// Generated by this command:
//
//	mockgen -destination=mocks/health_evaluator.go -package=mocks . HealthEvaluator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/benebsworth/paprika/api/pipelines/v1alpha1"
	health "github.com/benebsworth/paprika/health"
	gomock "go.uber.org/mock/gomock"
)

// MockHealthEvaluator is a mock of HealthEvaluator interface.
type MockHealthEvaluator struct {
	ctrl     *gomock.Controller
	recorder *MockHealthEvaluatorMockRecorder
	isgomock struct{}
}

// MockHealthEvaluatorMockRecorder is the mock recorder for MockHealthEvaluator.
type MockHealthEvaluatorMockRecorder struct {
	mock *MockHealthEvaluator
}

// NewMockHealthEvaluator creates a new mock instance.
func NewMockHealthEvaluator(ctrl *gomock.Controller) *MockHealthEvaluator {
	mock := &MockHealthEvaluator{ctrl: ctrl}
	mock.recorder = &MockHealthEvaluatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthEvaluator) EXPECT() *MockHealthEvaluatorMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockHealthEvaluator) Evaluate(ctx context.Context, check v1alpha1.HealthCheck, app *v1alpha1.Application) health.EvalResult {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", ctx, check, app)
	ret0, _ := ret[0].(health.EvalResult)
	return ret0
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockHealthEvaluatorMockRecorder) Evaluate(ctx, check, app any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockHealthEvaluator)(nil).Evaluate), ctx, check, app)
}
