// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/health (interfaces: ResourceHealthChecker)
//
// Generated by this command:
//
//	mockgen -destination=mocks/resource_health_checker.go -package=mocks . ResourceHealthChecker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	v1alpha1 "github.com/benebsworth/paprika/api/pipelines/v1alpha1"
	gomock "go.uber.org/mock/gomock"
)

// MockResourceHealthChecker is a mock of ResourceHealthChecker interface.
type MockResourceHealthChecker struct {
	ctrl     *gomock.Controller
	recorder *MockResourceHealthCheckerMockRecorder
	isgomock struct{}
}

// MockResourceHealthCheckerMockRecorder is the mock recorder for MockResourceHealthChecker.
type MockResourceHealthCheckerMockRecorder struct {
	mock *MockResourceHealthChecker
}

// NewMockResourceHealthChecker creates a new mock instance.
func NewMockResourceHealthChecker(ctrl *gomock.Controller) *MockResourceHealthChecker {
	mock := &MockResourceHealthChecker{ctrl: ctrl}
	mock.recorder = &MockResourceHealthCheckerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceHealthChecker) EXPECT() *MockResourceHealthCheckerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockResourceHealthChecker) Check(ctx context.Context, kind, name, namespace string) v1alpha1.ResourceHealth {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx, kind, name, namespace)
	ret0, _ := ret[0].(v1alpha1.ResourceHealth)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockResourceHealthCheckerMockRecorder) Check(ctx, kind, name, namespace any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockResourceHealthChecker)(nil).Check), ctx, kind, name, namespace)
}
