apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-demo-app-stable
  labels:
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/instance: {{ .Release.Name }}
    track: stable
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/instance: {{ .Release.Name }}
    track: stable
---
{{- $canaryWeight := .Values.canaryWeight | int -}}
{{- if gt $canaryWeight 0 }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-demo-app-canary
  labels:
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/instance: {{ .Release.Name }}
    track: canary
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: demo-app
    app.kubernetes.io/instance: {{ .Release.Name }}
    track: canary
{{- end }}