// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/benebsworth/paprika/internal/api (interfaces: Evaluator)
//
// Generated by this command:
//
//	mockgen -destination=mocks/evaluator.go -package=mocks . Evaluator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	policy "github.com/benebsworth/paprika/internal/policy"
	gomock "go.uber.org/mock/gomock"
)

// MockEvaluator is a mock of Evaluator interface.
type MockEvaluator struct {
	ctrl     *gomock.Controller
	recorder *MockEvaluatorMockRecorder
	isgomock struct{}
}

// MockEvaluatorMockRecorder is the mock recorder for MockEvaluator.
type MockEvaluatorMockRecorder struct {
	mock *MockEvaluator
}

// NewMockEvaluator creates a new mock instance.
func NewMockEvaluator(ctrl *gomock.Controller) *MockEvaluator {
	mock := &MockEvaluator{ctrl: ctrl}
	mock.recorder = &MockEvaluatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEvaluator) EXPECT() *MockEvaluatorMockRecorder {
	return m.recorder
}

// Evaluate mocks base method.
func (m *MockEvaluator) Evaluate(ctx context.Context, bundle []byte, opts policy.EvaluateOptions) (*policy.EvaluationResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Evaluate", ctx, bundle, opts)
	ret0, _ := ret[0].(*policy.EvaluationResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Evaluate indicates an expected call of Evaluate.
func (mr *MockEvaluatorMockRecorder) Evaluate(ctx, bundle, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Evaluate", reflect.TypeOf((*MockEvaluator)(nil).Evaluate), ctx, bundle, opts)
}
