{{- if .Values.agent.vpa.enabled }}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "paprika.resourceName" (dict "suffix" "agent" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "paprika.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: agent
spec:
  targetRef:
    apiVersion: apps/v1
    kind: DaemonSet
    name: {{ include "paprika.resourceName" (dict "suffix" "agent" "context" $) }}
  updatePolicy:
    updateMode: {{ .Values.agent.vpa.mode | quote }}
{{- end }}
