{{- if eq .Values.mode "api" }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "paprika.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    control-plane: controller-manager
  name: {{ include "paprika.resourceName" (dict "suffix" "manager-api-service" "context" $) }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: api
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/name: {{ include "paprika.name" . }}
    control-plane: controller-manager
  type: ClusterIP
{{- end }}
