{{- if and .Values.manager.pdb.enabled (not .Values.manager.sharding.enabled) (or (not (hasKey .Values.manager "enabled")) (.Values.manager.enabled)) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "paprika.resourceName" (dict "suffix" "controller-manager" "context" $) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "paprika.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    control-plane: controller-manager
spec:
  minAvailable: {{ .Values.manager.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "paprika.name" . }}
      control-plane: controller-manager
{{- end }}
